drop extension if exists "pg_net";


  create table "public"."avisos" (
    "id" bigint generated by default as identity not null,
    "aviso" character varying(255) not null,
    "data" character varying(255) not null
      );



  create table "public"."encomendas" (
    "id" bigint generated by default as identity not null,
    "hora_entrega" timestamp(6) without time zone not null,
    "remetente" character varying(255) not null,
    "funcionario_id" bigint not null,
    "morador_id" bigint not null
      );



  create table "public"."funcionarios" (
    "id" bigint generated by default as identity not null,
    "cargo" character varying(255) not null,
    "cpf" character varying(255) not null,
    "email" character varying(255) not null,
    "nome" character varying(255) not null,
    "rg" character varying(255) not null,
    "telefone" character varying(255) not null,
    "fk_user" bigint
      );



  create table "public"."locais" (
    "id" bigint generated by default as identity not null,
    "capacidade" integer not null,
    "nome" character varying(255) not null
      );



  create table "public"."moradores" (
    "id" bigint generated by default as identity not null,
    "apartamento" integer not null,
    "bloco" character(1) not null,
    "cpf" character varying(255) not null,
    "email" character varying(255) not null,
    "nome" character varying(255) not null,
    "rg" character varying(255),
    "telefone" character varying(255),
    "fk_user" bigint
      );



  create table "public"."reclamacoes" (
    "id" bigint generated by default as identity not null,
    "nome" character varying(255),
    "reclamacao" character varying(255),
    "fk_morador" bigint
      );



  create table "public"."reservas" (
    "id" bigint generated by default as identity not null,
    "data" date not null,
    "local_id" bigint not null,
    "morador_id" bigint not null
      );



  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "categoria" character varying(255) not null,
    "cpf" character varying(255) not null,
    "senha" character varying(255) not null
      );



  create table "public"."visitantes" (
    "id" bigint generated by default as identity not null,
    "cpf" character varying(255),
    "nome" character varying(255) not null,
    "rg" character varying(255) not null,
    "telefone" character varying(255),
    "funcionario_id" bigint not null,
    "morador_id" bigint not null
      );


CREATE UNIQUE INDEX avisos_pkey ON public.avisos USING btree (id);

CREATE UNIQUE INDEX encomendas_pkey ON public.encomendas USING btree (id);

CREATE UNIQUE INDEX funcionarios_pkey ON public.funcionarios USING btree (id);

CREATE UNIQUE INDEX locais_pkey ON public.locais USING btree (id);

CREATE UNIQUE INDEX moradores_pkey ON public.moradores USING btree (id);

CREATE UNIQUE INDEX reclamacoes_pkey ON public.reclamacoes USING btree (id);

CREATE UNIQUE INDEX reservas_pkey ON public.reservas USING btree (id);

CREATE UNIQUE INDEX uk1pga1fiak1swwsqbxl328q2qr ON public.moradores USING btree (cpf);

CREATE UNIQUE INDEX uk6kjp10kpu332ce8dhlwwe2sin ON public.funcionarios USING btree (rg);

CREATE UNIQUE INDEX uk6ykj99wearulush38401ayk8t ON public.moradores USING btree (email);

CREATE UNIQUE INDEX uk7gfqyj9t2i54sy9q0a9dho856 ON public.visitantes USING btree (rg);

CREATE UNIQUE INDEX uk7kqluf7wl0oxs7n90fpya03ss ON public.users USING btree (cpf);

CREATE UNIQUE INDEX uk9eplb962yievbe8vq9n1t860s ON public.reclamacoes USING btree (fk_morador);

CREATE UNIQUE INDEX ukc481678h2nq80gfbwg0kk5f1f ON public.visitantes USING btree (cpf);

CREATE UNIQUE INDEX ukd5a73bi3k2ilof35177pvkrsk ON public.moradores USING btree (fk_user);

CREATE UNIQUE INDEX uke0xb0ldevxbvutrllgobqfd1j ON public.funcionarios USING btree (fk_user);

CREATE UNIQUE INDEX ukmqe8kkst1yn1vfejqtvdy3wcu ON public.moradores USING btree (rg);

CREATE UNIQUE INDEX uko60knm5wr28plxwo0clyg2eu4 ON public.funcionarios USING btree (email);

CREATE UNIQUE INDEX ukringk47bybtxxhm0aurt3c21q ON public.locais USING btree (nome);

CREATE UNIQUE INDEX ukrrykmyf711s2n7maopibw47s0 ON public.funcionarios USING btree (cpf);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX visitantes_pkey ON public.visitantes USING btree (id);

alter table "public"."avisos" add constraint "avisos_pkey" PRIMARY KEY using index "avisos_pkey";

alter table "public"."encomendas" add constraint "encomendas_pkey" PRIMARY KEY using index "encomendas_pkey";

alter table "public"."funcionarios" add constraint "funcionarios_pkey" PRIMARY KEY using index "funcionarios_pkey";

alter table "public"."locais" add constraint "locais_pkey" PRIMARY KEY using index "locais_pkey";

alter table "public"."moradores" add constraint "moradores_pkey" PRIMARY KEY using index "moradores_pkey";

alter table "public"."reclamacoes" add constraint "reclamacoes_pkey" PRIMARY KEY using index "reclamacoes_pkey";

alter table "public"."reservas" add constraint "reservas_pkey" PRIMARY KEY using index "reservas_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."visitantes" add constraint "visitantes_pkey" PRIMARY KEY using index "visitantes_pkey";

alter table "public"."encomendas" add constraint "fk31kn3bndvuum2d07beo42q9kd" FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) not valid;

alter table "public"."encomendas" validate constraint "fk31kn3bndvuum2d07beo42q9kd";

alter table "public"."encomendas" add constraint "fk6ki8pbrd66vtpt7xevq868q6g" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."encomendas" validate constraint "fk6ki8pbrd66vtpt7xevq868q6g";

alter table "public"."funcionarios" add constraint "fk7mf3shfr7b1j3cmxx1fh559vp" FOREIGN KEY (fk_user) REFERENCES public.users(id) not valid;

alter table "public"."funcionarios" validate constraint "fk7mf3shfr7b1j3cmxx1fh559vp";

alter table "public"."funcionarios" add constraint "uk6kjp10kpu332ce8dhlwwe2sin" UNIQUE using index "uk6kjp10kpu332ce8dhlwwe2sin";

alter table "public"."funcionarios" add constraint "uke0xb0ldevxbvutrllgobqfd1j" UNIQUE using index "uke0xb0ldevxbvutrllgobqfd1j";

alter table "public"."funcionarios" add constraint "uko60knm5wr28plxwo0clyg2eu4" UNIQUE using index "uko60knm5wr28plxwo0clyg2eu4";

alter table "public"."funcionarios" add constraint "ukrrykmyf711s2n7maopibw47s0" UNIQUE using index "ukrrykmyf711s2n7maopibw47s0";

alter table "public"."locais" add constraint "ukringk47bybtxxhm0aurt3c21q" UNIQUE using index "ukringk47bybtxxhm0aurt3c21q";

alter table "public"."moradores" add constraint "fkqr8u40httmaug4dd2knkdb697" FOREIGN KEY (fk_user) REFERENCES public.users(id) not valid;

alter table "public"."moradores" validate constraint "fkqr8u40httmaug4dd2knkdb697";

alter table "public"."moradores" add constraint "uk1pga1fiak1swwsqbxl328q2qr" UNIQUE using index "uk1pga1fiak1swwsqbxl328q2qr";

alter table "public"."moradores" add constraint "uk6ykj99wearulush38401ayk8t" UNIQUE using index "uk6ykj99wearulush38401ayk8t";

alter table "public"."moradores" add constraint "ukd5a73bi3k2ilof35177pvkrsk" UNIQUE using index "ukd5a73bi3k2ilof35177pvkrsk";

alter table "public"."moradores" add constraint "ukmqe8kkst1yn1vfejqtvdy3wcu" UNIQUE using index "ukmqe8kkst1yn1vfejqtvdy3wcu";

alter table "public"."reclamacoes" add constraint "fkb6wb7dhx4nry0qnjj87fq5bmm" FOREIGN KEY (fk_morador) REFERENCES public.moradores(id) not valid;

alter table "public"."reclamacoes" validate constraint "fkb6wb7dhx4nry0qnjj87fq5bmm";

alter table "public"."reclamacoes" add constraint "uk9eplb962yievbe8vq9n1t860s" UNIQUE using index "uk9eplb962yievbe8vq9n1t860s";

alter table "public"."reservas" add constraint "fkmlupau8oyqfgf4vaof15vq6l7" FOREIGN KEY (local_id) REFERENCES public.locais(id) not valid;

alter table "public"."reservas" validate constraint "fkmlupau8oyqfgf4vaof15vq6l7";

alter table "public"."reservas" add constraint "fks5wsc18biv3cqiq65ae0we280" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."reservas" validate constraint "fks5wsc18biv3cqiq65ae0we280";

alter table "public"."users" add constraint "uk7kqluf7wl0oxs7n90fpya03ss" UNIQUE using index "uk7kqluf7wl0oxs7n90fpya03ss";

alter table "public"."visitantes" add constraint "fkdpuwbgbhb26ccng43u9w08a30" FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) not valid;

alter table "public"."visitantes" validate constraint "fkdpuwbgbhb26ccng43u9w08a30";

alter table "public"."visitantes" add constraint "fkl2vfmtc2icju76haimayangxc" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."visitantes" validate constraint "fkl2vfmtc2icju76haimayangxc";

alter table "public"."visitantes" add constraint "uk7gfqyj9t2i54sy9q0a9dho856" UNIQUE using index "uk7gfqyj9t2i54sy9q0a9dho856";

alter table "public"."visitantes" add constraint "ukc481678h2nq80gfbwg0kk5f1f" UNIQUE using index "ukc481678h2nq80gfbwg0kk5f1f";

grant delete on table "public"."avisos" to "anon";

grant insert on table "public"."avisos" to "anon";

grant references on table "public"."avisos" to "anon";

grant select on table "public"."avisos" to "anon";

grant trigger on table "public"."avisos" to "anon";

grant truncate on table "public"."avisos" to "anon";

grant update on table "public"."avisos" to "anon";

grant delete on table "public"."avisos" to "authenticated";

grant insert on table "public"."avisos" to "authenticated";

grant references on table "public"."avisos" to "authenticated";

grant select on table "public"."avisos" to "authenticated";

grant trigger on table "public"."avisos" to "authenticated";

grant truncate on table "public"."avisos" to "authenticated";

grant update on table "public"."avisos" to "authenticated";

grant delete on table "public"."avisos" to "service_role";

grant insert on table "public"."avisos" to "service_role";

grant references on table "public"."avisos" to "service_role";

grant select on table "public"."avisos" to "service_role";

grant trigger on table "public"."avisos" to "service_role";

grant truncate on table "public"."avisos" to "service_role";

grant update on table "public"."avisos" to "service_role";

grant delete on table "public"."encomendas" to "anon";

grant insert on table "public"."encomendas" to "anon";

grant references on table "public"."encomendas" to "anon";

grant select on table "public"."encomendas" to "anon";

grant trigger on table "public"."encomendas" to "anon";

grant truncate on table "public"."encomendas" to "anon";

grant update on table "public"."encomendas" to "anon";

grant delete on table "public"."encomendas" to "authenticated";

grant insert on table "public"."encomendas" to "authenticated";

grant references on table "public"."encomendas" to "authenticated";

grant select on table "public"."encomendas" to "authenticated";

grant trigger on table "public"."encomendas" to "authenticated";

grant truncate on table "public"."encomendas" to "authenticated";

grant update on table "public"."encomendas" to "authenticated";

grant delete on table "public"."encomendas" to "service_role";

grant insert on table "public"."encomendas" to "service_role";

grant references on table "public"."encomendas" to "service_role";

grant select on table "public"."encomendas" to "service_role";

grant trigger on table "public"."encomendas" to "service_role";

grant truncate on table "public"."encomendas" to "service_role";

grant update on table "public"."encomendas" to "service_role";

grant delete on table "public"."funcionarios" to "anon";

grant insert on table "public"."funcionarios" to "anon";

grant references on table "public"."funcionarios" to "anon";

grant select on table "public"."funcionarios" to "anon";

grant trigger on table "public"."funcionarios" to "anon";

grant truncate on table "public"."funcionarios" to "anon";

grant update on table "public"."funcionarios" to "anon";

grant delete on table "public"."funcionarios" to "authenticated";

grant insert on table "public"."funcionarios" to "authenticated";

grant references on table "public"."funcionarios" to "authenticated";

grant select on table "public"."funcionarios" to "authenticated";

grant trigger on table "public"."funcionarios" to "authenticated";

grant truncate on table "public"."funcionarios" to "authenticated";

grant update on table "public"."funcionarios" to "authenticated";

grant delete on table "public"."funcionarios" to "service_role";

grant insert on table "public"."funcionarios" to "service_role";

grant references on table "public"."funcionarios" to "service_role";

grant select on table "public"."funcionarios" to "service_role";

grant trigger on table "public"."funcionarios" to "service_role";

grant truncate on table "public"."funcionarios" to "service_role";

grant update on table "public"."funcionarios" to "service_role";

grant delete on table "public"."locais" to "anon";

grant insert on table "public"."locais" to "anon";

grant references on table "public"."locais" to "anon";

grant select on table "public"."locais" to "anon";

grant trigger on table "public"."locais" to "anon";

grant truncate on table "public"."locais" to "anon";

grant update on table "public"."locais" to "anon";

grant delete on table "public"."locais" to "authenticated";

grant insert on table "public"."locais" to "authenticated";

grant references on table "public"."locais" to "authenticated";

grant select on table "public"."locais" to "authenticated";

grant trigger on table "public"."locais" to "authenticated";

grant truncate on table "public"."locais" to "authenticated";

grant update on table "public"."locais" to "authenticated";

grant delete on table "public"."locais" to "service_role";

grant insert on table "public"."locais" to "service_role";

grant references on table "public"."locais" to "service_role";

grant select on table "public"."locais" to "service_role";

grant trigger on table "public"."locais" to "service_role";

grant truncate on table "public"."locais" to "service_role";

grant update on table "public"."locais" to "service_role";

grant delete on table "public"."moradores" to "anon";

grant insert on table "public"."moradores" to "anon";

grant references on table "public"."moradores" to "anon";

grant select on table "public"."moradores" to "anon";

grant trigger on table "public"."moradores" to "anon";

grant truncate on table "public"."moradores" to "anon";

grant update on table "public"."moradores" to "anon";

grant delete on table "public"."moradores" to "authenticated";

grant insert on table "public"."moradores" to "authenticated";

grant references on table "public"."moradores" to "authenticated";

grant select on table "public"."moradores" to "authenticated";

grant trigger on table "public"."moradores" to "authenticated";

grant truncate on table "public"."moradores" to "authenticated";

grant update on table "public"."moradores" to "authenticated";

grant delete on table "public"."moradores" to "service_role";

grant insert on table "public"."moradores" to "service_role";

grant references on table "public"."moradores" to "service_role";

grant select on table "public"."moradores" to "service_role";

grant trigger on table "public"."moradores" to "service_role";

grant truncate on table "public"."moradores" to "service_role";

grant update on table "public"."moradores" to "service_role";

grant delete on table "public"."reclamacoes" to "anon";

grant insert on table "public"."reclamacoes" to "anon";

grant references on table "public"."reclamacoes" to "anon";

grant select on table "public"."reclamacoes" to "anon";

grant trigger on table "public"."reclamacoes" to "anon";

grant truncate on table "public"."reclamacoes" to "anon";

grant update on table "public"."reclamacoes" to "anon";

grant delete on table "public"."reclamacoes" to "authenticated";

grant insert on table "public"."reclamacoes" to "authenticated";

grant references on table "public"."reclamacoes" to "authenticated";

grant select on table "public"."reclamacoes" to "authenticated";

grant trigger on table "public"."reclamacoes" to "authenticated";

grant truncate on table "public"."reclamacoes" to "authenticated";

grant update on table "public"."reclamacoes" to "authenticated";

grant delete on table "public"."reclamacoes" to "service_role";

grant insert on table "public"."reclamacoes" to "service_role";

grant references on table "public"."reclamacoes" to "service_role";

grant select on table "public"."reclamacoes" to "service_role";

grant trigger on table "public"."reclamacoes" to "service_role";

grant truncate on table "public"."reclamacoes" to "service_role";

grant update on table "public"."reclamacoes" to "service_role";

grant delete on table "public"."reservas" to "anon";

grant insert on table "public"."reservas" to "anon";

grant references on table "public"."reservas" to "anon";

grant select on table "public"."reservas" to "anon";

grant trigger on table "public"."reservas" to "anon";

grant truncate on table "public"."reservas" to "anon";

grant update on table "public"."reservas" to "anon";

grant delete on table "public"."reservas" to "authenticated";

grant insert on table "public"."reservas" to "authenticated";

grant references on table "public"."reservas" to "authenticated";

grant select on table "public"."reservas" to "authenticated";

grant trigger on table "public"."reservas" to "authenticated";

grant truncate on table "public"."reservas" to "authenticated";

grant update on table "public"."reservas" to "authenticated";

grant delete on table "public"."reservas" to "service_role";

grant insert on table "public"."reservas" to "service_role";

grant references on table "public"."reservas" to "service_role";

grant select on table "public"."reservas" to "service_role";

grant trigger on table "public"."reservas" to "service_role";

grant truncate on table "public"."reservas" to "service_role";

grant update on table "public"."reservas" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."visitantes" to "anon";

grant insert on table "public"."visitantes" to "anon";

grant references on table "public"."visitantes" to "anon";

grant select on table "public"."visitantes" to "anon";

grant trigger on table "public"."visitantes" to "anon";

grant truncate on table "public"."visitantes" to "anon";

grant update on table "public"."visitantes" to "anon";

grant delete on table "public"."visitantes" to "authenticated";

grant insert on table "public"."visitantes" to "authenticated";

grant references on table "public"."visitantes" to "authenticated";

grant select on table "public"."visitantes" to "authenticated";

grant trigger on table "public"."visitantes" to "authenticated";

grant truncate on table "public"."visitantes" to "authenticated";

grant update on table "public"."visitantes" to "authenticated";

grant delete on table "public"."visitantes" to "service_role";

grant insert on table "public"."visitantes" to "service_role";

grant references on table "public"."visitantes" to "service_role";

grant select on table "public"."visitantes" to "service_role";

grant trigger on table "public"."visitantes" to "service_role";

grant truncate on table "public"."visitantes" to "service_role";

grant update on table "public"."visitantes" to "service_role";


