drop extension if exists "pg_net";


  create table "public"."CSTB001_USER" (
    "ID_USER" bigint generated by default as identity not null,
    "NR_CPF" character varying(11) not null,
    "NO_PESSOA" character varying(150) not null,
    "NR_RG" character varying(20),
    "EM_PESSOAL" character varying(150) not null,
    "NR_CELULAR" character varying(15),
    "ID_CATEGORIA_ACESSO" bigint not null,
    "TX_SENHA" character varying(255) not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB001_USER" enable row level security;


  create table "public"."CSTB002_MORADOR" (
    "ID_MORADOR" bigint generated by default as identity not null,
    "ID_USER" bigint not null,
    "IC_BLOCO" character varying(10) not null,
    "NR_APARTAMENTO" integer not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB002_MORADOR" enable row level security;


  create table "public"."CSTB003_FUNCIONARIO" (
    "ID_FUNCIONARIO" bigint generated by default as identity not null,
    "ID_USER" bigint not null,
    "ID_CATEGORIA_CARGO" bigint not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB003_FUNCIONARIO" enable row level security;


  create table "public"."CSTB004_VISITANTE" (
    "ID_VISITANTE" bigint generated by default as identity not null,
    "NO_PESSOA" character varying(150) not null,
    "NR_CPF" character varying(11),
    "NR_RG" character varying(20) not null,
    "NR_TELEFONE" character varying(15),
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB004_VISITANTE" enable row level security;


  create table "public"."CSTB005_ENCOMENDA" (
    "ID_ENCOMENDA" bigint generated by default as identity not null,
    "ID_MORADOR" bigint not null,
    "ID_FUNCIONARIO" bigint not null,
    "NO_REMETENTE" character varying(150) not null,
    "ID_CATEGORIA_ENCOMENDA" bigint not null,
    "DT_RECEBIDO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "DT_RETIRADO" timestamp without time zone,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB005_ENCOMENDA" enable row level security;


  create table "public"."CSTB006_RECLAMACAO" (
    "ID_RECLAMACAO" bigint generated by default as identity not null,
    "ID_MORADOR" bigint not null,
    "TX_TITULO" character varying(100) not null,
    "DS_RECLAMACAO" text not null,
    "ID_CATEGORIA_RECLAMACAO" bigint not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB006_RECLAMACAO" enable row level security;


  create table "public"."CSTB007_AVISO" (
    "ID_AVISO" bigint generated by default as identity not null,
    "ID_USER" bigint not null,
    "TX_TITULO" character varying(100) not null,
    "DS_AVISO" text not null,
    "DT_EXPIRACAO" timestamp without time zone,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB007_AVISO" enable row level security;


  create table "public"."CSTB008_LOCAL" (
    "ID_LOCAL" bigint generated by default as identity not null,
    "NO_LOCAL" character varying(100) not null,
    "NR_CAPACIDADE" integer not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB008_LOCAL" enable row level security;


  create table "public"."CSTB009_RESERVA" (
    "ID_RESERVA" bigint generated by default as identity not null,
    "ID_MORADOR" bigint not null,
    "ID_LOCAL" bigint not null,
    "DT_INICIO" timestamp without time zone not null,
    "DT_FIM" timestamp without time zone not null,
    "ID_CATEGORIA_RESERVA" bigint not null,
    "LG_ATIVO" boolean not null default true
      );


alter table "public"."CSTB009_RESERVA" enable row level security;


  create table "public"."CSTB010_CATEGORIA_ACESSO" (
    "ID_CATEGORIA_ACESSO" bigint generated by default as identity not null,
    "NO_CATEGORIA_ACESSO" character varying(20) not null
      );


alter table "public"."CSTB010_CATEGORIA_ACESSO" enable row level security;


  create table "public"."CSTB011_CATEGORIA_CARGO" (
    "ID_CATEGORIA_CARGO" bigint generated by default as identity not null,
    "NO_CATEGORIA_CARGO" character varying(20) not null
      );


alter table "public"."CSTB011_CATEGORIA_CARGO" enable row level security;


  create table "public"."CSTB012_CATEGORIA_ENCOMENDA" (
    "ID_CATEGORIA_ENCOMENDA" bigint generated by default as identity not null,
    "NO_CATEGORIA_ENCOMENDA" character varying(20) not null
      );


alter table "public"."CSTB012_CATEGORIA_ENCOMENDA" enable row level security;


  create table "public"."CSTB013_CATEGORIA_RECLAMACAO" (
    "ID_CATEGORIA_RECLAMACAO" bigint generated by default as identity not null,
    "NO_CATEGORIA_RECLAMACAO" character varying(20) not null default 'ABERTA'::character varying
      );


alter table "public"."CSTB013_CATEGORIA_RECLAMACAO" enable row level security;


  create table "public"."CSTB014_CATEGORIA_RESERVA" (
    "ID_CATEGORIA_RESERVA" bigint generated by default as identity not null,
    "NO_CATEGORIA_RESERVA" character varying(20) not null default 'CONFIRMADA'::character varying
      );


alter table "public"."CSTB014_CATEGORIA_RESERVA" enable row level security;


  create table "public"."CSTB015_ACESSO_VISITANTE" (
    "ID_ACESSO" bigint generated by default as identity not null,
    "ID_VISITANTE" bigint not null,
    "ID_MORADOR" bigint not null,
    "ID_FUNCIONARIO" bigint not null,
    "DT_ENTRADA" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "DT_SAIDA" timestamp without time zone
      );


alter table "public"."CSTB015_ACESSO_VISITANTE" enable row level security;


  create table "public"."CSTBH001_USER" (
    "ID_HISTORICO" bigint generated by default as identity not null,
    "ID_USER" bigint generated by default as identity not null,
    "NR_CPF" character varying(11) not null,
    "NO_PESSOA" character varying(150) not null,
    "NR_RG" character varying(20),
    "EM_PESSOAL" character varying(150) not null,
    "NR_CELULAR" numeric(11,0),
    "ID_CATEGORIA_ACESSO" character varying(20) not null,
    "TX_SENHA" character varying(255) not null,
    "DH_ACAO_REGISTRO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "IC_ACAO_REGISTRO" character(1) not null,
    "ID_USER_USUARIO_ACAO_REGISTRO" bigint not null,
    "LG_ATIVO" boolean not null
      );


alter table "public"."CSTBH001_USER" enable row level security;


  create table "public"."CSTBH002_MORADOR" (
    "ID_HISTORICO" bigint generated by default as identity not null,
    "ID_MORADOR" bigint,
    "ID_USER" bigint,
    "IC_BLOCO" character varying(10),
    "NR_APARTAMENTO" integer,
    "LG_ATIVO" boolean,
    "DH_ACAO_REGISTRO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "IC_ACAO_REGISTRO" character(1) not null,
    "ID_USER_AUDITOR" bigint not null
      );


alter table "public"."CSTBH002_MORADOR" enable row level security;


  create table "public"."CSTBH003_FUNCIONARIO" (
    "ID_HISTORICO" bigint generated by default as identity not null,
    "ID_FUNCIONARIO" bigint,
    "ID_USER" bigint,
    "ID_CATEGORIA_CARGO" bigint,
    "LG_ATIVO" boolean,
    "DH_ACAO_REGISTRO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "IC_ACAO_REGISTRO" character(1) not null,
    "ID_USER_AUDITOR" bigint not null
      );


alter table "public"."CSTBH003_FUNCIONARIO" enable row level security;


  create table "public"."CSTBH005_ENCOMENDA" (
    "ID_HISTORICO" bigint generated by default as identity not null,
    "ID_ENCOMENDA" bigint,
    "ID_MORADOR" bigint,
    "ID_FUNCIONARIO" bigint,
    "ID_CATEGORIA_ENCOMENDA" bigint,
    "DT_RETIRADO" timestamp without time zone,
    "LG_ATIVO" boolean,
    "DH_ACAO_REGISTRO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "IC_ACAO_REGISTRO" character(1) not null,
    "ID_USER_AUDITOR" bigint not null,
    "NO_REMETENTE" character varying,
    "DT_RECEBIDO" timestamp without time zone
      );


alter table "public"."CSTBH005_ENCOMENDA" enable row level security;


  create table "public"."CSTBH009_RESERVA" (
    "ID_HISTORICO" bigint generated by default as identity not null,
    "ID_RESERVA" bigint,
    "ID_MORADOR" bigint,
    "ID_LOCAL" bigint,
    "DT_INICIO" timestamp without time zone,
    "DT_FIM" timestamp without time zone,
    "ID_CATEGORIA_RESERVA" bigint,
    "LG_ATIVO" boolean,
    "DH_ACAO_REGISTRO" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "IC_ACAO_REGISTRO" character(1) not null,
    "ID_USER_AUDITOR" bigint not null
      );


alter table "public"."CSTBH009_RESERVA" enable row level security;


  create table "public"."avisos" (
    "id" bigint generated by default as identity not null,
    "aviso" character varying(255) not null,
    "data" character varying(255) not null
      );



  create table "public"."encomendas" (
    "id" bigint generated by default as identity not null,
    "hora_entrega" timestamp(6) without time zone not null,
    "remetente" character varying(255) not null,
    "funcionario_id" bigint not null,
    "morador_id" bigint not null
      );



  create table "public"."funcionarios" (
    "id" bigint generated by default as identity not null,
    "cargo" character varying(255) not null,
    "cpf" character varying(255) not null,
    "email" character varying(255) not null,
    "nome" character varying(255) not null,
    "rg" character varying(255) not null,
    "telefone" character varying(255) not null,
    "fk_user" bigint
      );



  create table "public"."locais" (
    "id" bigint generated by default as identity not null,
    "capacidade" integer not null,
    "nome" character varying(255) not null
      );



  create table "public"."moradores" (
    "id" bigint generated by default as identity not null,
    "apartamento" integer not null,
    "bloco" character(1) not null,
    "cpf" character varying(255) not null,
    "email" character varying(255) not null,
    "nome" character varying(255) not null,
    "rg" character varying(255),
    "telefone" character varying(255),
    "fk_user" bigint
      );



  create table "public"."reclamacoes" (
    "id" bigint generated by default as identity not null,
    "nome" character varying(255),
    "reclamacao" character varying(255),
    "fk_morador" bigint
      );



  create table "public"."reservas" (
    "id" bigint generated by default as identity not null,
    "data" date not null,
    "local_id" bigint not null,
    "morador_id" bigint not null
      );



  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "categoria" character varying(255) not null,
    "cpf" character varying(255) not null,
    "senha" character varying(255) not null
      );



  create table "public"."visitantes" (
    "id" bigint generated by default as identity not null,
    "cpf" character varying(255),
    "nome" character varying(255) not null,
    "rg" character varying(255) not null,
    "telefone" character varying(255),
    "funcionario_id" bigint not null,
    "morador_id" bigint not null
      );


CREATE UNIQUE INDEX "CSTB001_USER_EM_PESSOAL_key" ON public."CSTB001_USER" USING btree ("EM_PESSOAL");

CREATE UNIQUE INDEX "CSTB001_USER_NR_CPF_key" ON public."CSTB001_USER" USING btree ("NR_CPF");

CREATE UNIQUE INDEX "CSTB001_USER_pkey" ON public."CSTB001_USER" USING btree ("ID_USER");

CREATE UNIQUE INDEX "CSTB002_MORADOR_ID_USER_key" ON public."CSTB002_MORADOR" USING btree ("ID_USER");

CREATE UNIQUE INDEX "CSTB002_MORADOR_pkey" ON public."CSTB002_MORADOR" USING btree ("ID_MORADOR");

CREATE UNIQUE INDEX "CSTB003_FUNCIONARIO_ID_USER_key" ON public."CSTB003_FUNCIONARIO" USING btree ("ID_USER");

CREATE UNIQUE INDEX "CSTB003_FUNCIONARIO_pkey" ON public."CSTB003_FUNCIONARIO" USING btree ("ID_FUNCIONARIO");

CREATE UNIQUE INDEX "CSTB004_VISITANTE_NR_CPF_key" ON public."CSTB004_VISITANTE" USING btree ("NR_CPF");

CREATE UNIQUE INDEX "CSTB004_VISITANTE_NR_RG_key" ON public."CSTB004_VISITANTE" USING btree ("NR_RG");

CREATE UNIQUE INDEX "CSTB004_VISITANTE_pkey" ON public."CSTB004_VISITANTE" USING btree ("ID_VISITANTE");

CREATE UNIQUE INDEX "CSTB005_ENCOMENDA_pkey" ON public."CSTB005_ENCOMENDA" USING btree ("ID_ENCOMENDA");

CREATE UNIQUE INDEX "CSTB006_RECLAMACAO_pkey" ON public."CSTB006_RECLAMACAO" USING btree ("ID_RECLAMACAO");

CREATE UNIQUE INDEX "CSTB007_AVISO_pkey" ON public."CSTB007_AVISO" USING btree ("ID_AVISO");

CREATE UNIQUE INDEX "CSTB008_LOCAL_NO_LOCAL_key" ON public."CSTB008_LOCAL" USING btree ("NO_LOCAL");

CREATE UNIQUE INDEX "CSTB008_LOCAL_pkey" ON public."CSTB008_LOCAL" USING btree ("ID_LOCAL");

CREATE UNIQUE INDEX "CSTB009_RESERVA_pkey" ON public."CSTB009_RESERVA" USING btree ("ID_RESERVA");

CREATE UNIQUE INDEX "CSTB010_CATEGORIA_ACESSO_pkey" ON public."CSTB010_CATEGORIA_ACESSO" USING btree ("ID_CATEGORIA_ACESSO");

CREATE UNIQUE INDEX "CSTB011_CATEGORIA_CARGO_pkey" ON public."CSTB011_CATEGORIA_CARGO" USING btree ("ID_CATEGORIA_CARGO");

CREATE UNIQUE INDEX "CSTB012_CATEGORIA_ENCOMENDA_pkey" ON public."CSTB012_CATEGORIA_ENCOMENDA" USING btree ("ID_CATEGORIA_ENCOMENDA");

CREATE UNIQUE INDEX "CSTB013_CATEGORIA_RECLAMACAO_pkey" ON public."CSTB013_CATEGORIA_RECLAMACAO" USING btree ("ID_CATEGORIA_RECLAMACAO");

CREATE UNIQUE INDEX "CSTB014_CATEGORIA_RESERVA_pkey" ON public."CSTB014_CATEGORIA_RESERVA" USING btree ("ID_CATEGORIA_RESERVA");

CREATE UNIQUE INDEX "CSTB015_ACESSO_VISITANTE_pkey" ON public."CSTB015_ACESSO_VISITANTE" USING btree ("ID_ACESSO");

CREATE UNIQUE INDEX "CSTBH001_USER_pkey" ON public."CSTBH001_USER" USING btree ("ID_HISTORICO", "ID_USER");

CREATE UNIQUE INDEX "CSTBH002_MORADOR_pkey" ON public."CSTBH002_MORADOR" USING btree ("ID_HISTORICO");

CREATE UNIQUE INDEX "CSTBH003_FUNCIONARIO_pkey" ON public."CSTBH003_FUNCIONARIO" USING btree ("ID_HISTORICO");

CREATE UNIQUE INDEX "CSTBH005_ENCOMENDA_pkey" ON public."CSTBH005_ENCOMENDA" USING btree ("ID_HISTORICO");

CREATE UNIQUE INDEX "CSTBH009_RESERVA_pkey" ON public."CSTBH009_RESERVA" USING btree ("ID_HISTORICO");

CREATE UNIQUE INDEX avisos_pkey ON public.avisos USING btree (id);

CREATE UNIQUE INDEX encomendas_pkey ON public.encomendas USING btree (id);

CREATE UNIQUE INDEX funcionarios_pkey ON public.funcionarios USING btree (id);

CREATE UNIQUE INDEX locais_pkey ON public.locais USING btree (id);

CREATE UNIQUE INDEX moradores_pkey ON public.moradores USING btree (id);

CREATE UNIQUE INDEX reclamacoes_pkey ON public.reclamacoes USING btree (id);

CREATE UNIQUE INDEX reservas_pkey ON public.reservas USING btree (id);

CREATE UNIQUE INDEX uk1pga1fiak1swwsqbxl328q2qr ON public.moradores USING btree (cpf);

CREATE UNIQUE INDEX uk6kjp10kpu332ce8dhlwwe2sin ON public.funcionarios USING btree (rg);

CREATE UNIQUE INDEX uk6ykj99wearulush38401ayk8t ON public.moradores USING btree (email);

CREATE UNIQUE INDEX uk7gfqyj9t2i54sy9q0a9dho856 ON public.visitantes USING btree (rg);

CREATE UNIQUE INDEX uk7kqluf7wl0oxs7n90fpya03ss ON public.users USING btree (cpf);

CREATE UNIQUE INDEX uk9eplb962yievbe8vq9n1t860s ON public.reclamacoes USING btree (fk_morador);

CREATE UNIQUE INDEX ukc481678h2nq80gfbwg0kk5f1f ON public.visitantes USING btree (cpf);

CREATE UNIQUE INDEX ukd5a73bi3k2ilof35177pvkrsk ON public.moradores USING btree (fk_user);

CREATE UNIQUE INDEX uke0xb0ldevxbvutrllgobqfd1j ON public.funcionarios USING btree (fk_user);

CREATE UNIQUE INDEX ukmqe8kkst1yn1vfejqtvdy3wcu ON public.moradores USING btree (rg);

CREATE UNIQUE INDEX uko60knm5wr28plxwo0clyg2eu4 ON public.funcionarios USING btree (email);

CREATE UNIQUE INDEX ukringk47bybtxxhm0aurt3c21q ON public.locais USING btree (nome);

CREATE UNIQUE INDEX ukrrykmyf711s2n7maopibw47s0 ON public.funcionarios USING btree (cpf);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX visitantes_pkey ON public.visitantes USING btree (id);

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_pkey" PRIMARY KEY using index "CSTB001_USER_pkey";

alter table "public"."CSTB002_MORADOR" add constraint "CSTB002_MORADOR_pkey" PRIMARY KEY using index "CSTB002_MORADOR_pkey";

alter table "public"."CSTB003_FUNCIONARIO" add constraint "CSTB003_FUNCIONARIO_pkey" PRIMARY KEY using index "CSTB003_FUNCIONARIO_pkey";

alter table "public"."CSTB004_VISITANTE" add constraint "CSTB004_VISITANTE_pkey" PRIMARY KEY using index "CSTB004_VISITANTE_pkey";

alter table "public"."CSTB005_ENCOMENDA" add constraint "CSTB005_ENCOMENDA_pkey" PRIMARY KEY using index "CSTB005_ENCOMENDA_pkey";

alter table "public"."CSTB006_RECLAMACAO" add constraint "CSTB006_RECLAMACAO_pkey" PRIMARY KEY using index "CSTB006_RECLAMACAO_pkey";

alter table "public"."CSTB007_AVISO" add constraint "CSTB007_AVISO_pkey" PRIMARY KEY using index "CSTB007_AVISO_pkey";

alter table "public"."CSTB008_LOCAL" add constraint "CSTB008_LOCAL_pkey" PRIMARY KEY using index "CSTB008_LOCAL_pkey";

alter table "public"."CSTB009_RESERVA" add constraint "CSTB009_RESERVA_pkey" PRIMARY KEY using index "CSTB009_RESERVA_pkey";

alter table "public"."CSTB010_CATEGORIA_ACESSO" add constraint "CSTB010_CATEGORIA_ACESSO_pkey" PRIMARY KEY using index "CSTB010_CATEGORIA_ACESSO_pkey";

alter table "public"."CSTB011_CATEGORIA_CARGO" add constraint "CSTB011_CATEGORIA_CARGO_pkey" PRIMARY KEY using index "CSTB011_CATEGORIA_CARGO_pkey";

alter table "public"."CSTB012_CATEGORIA_ENCOMENDA" add constraint "CSTB012_CATEGORIA_ENCOMENDA_pkey" PRIMARY KEY using index "CSTB012_CATEGORIA_ENCOMENDA_pkey";

alter table "public"."CSTB013_CATEGORIA_RECLAMACAO" add constraint "CSTB013_CATEGORIA_RECLAMACAO_pkey" PRIMARY KEY using index "CSTB013_CATEGORIA_RECLAMACAO_pkey";

alter table "public"."CSTB014_CATEGORIA_RESERVA" add constraint "CSTB014_CATEGORIA_RESERVA_pkey" PRIMARY KEY using index "CSTB014_CATEGORIA_RESERVA_pkey";

alter table "public"."CSTB015_ACESSO_VISITANTE" add constraint "CSTB015_ACESSO_VISITANTE_pkey" PRIMARY KEY using index "CSTB015_ACESSO_VISITANTE_pkey";

alter table "public"."CSTBH001_USER" add constraint "CSTBH001_USER_pkey" PRIMARY KEY using index "CSTBH001_USER_pkey";

alter table "public"."CSTBH002_MORADOR" add constraint "CSTBH002_MORADOR_pkey" PRIMARY KEY using index "CSTBH002_MORADOR_pkey";

alter table "public"."CSTBH003_FUNCIONARIO" add constraint "CSTBH003_FUNCIONARIO_pkey" PRIMARY KEY using index "CSTBH003_FUNCIONARIO_pkey";

alter table "public"."CSTBH005_ENCOMENDA" add constraint "CSTBH005_ENCOMENDA_pkey" PRIMARY KEY using index "CSTBH005_ENCOMENDA_pkey";

alter table "public"."CSTBH009_RESERVA" add constraint "CSTBH009_RESERVA_pkey" PRIMARY KEY using index "CSTBH009_RESERVA_pkey";

alter table "public"."avisos" add constraint "avisos_pkey" PRIMARY KEY using index "avisos_pkey";

alter table "public"."encomendas" add constraint "encomendas_pkey" PRIMARY KEY using index "encomendas_pkey";

alter table "public"."funcionarios" add constraint "funcionarios_pkey" PRIMARY KEY using index "funcionarios_pkey";

alter table "public"."locais" add constraint "locais_pkey" PRIMARY KEY using index "locais_pkey";

alter table "public"."moradores" add constraint "moradores_pkey" PRIMARY KEY using index "moradores_pkey";

alter table "public"."reclamacoes" add constraint "reclamacoes_pkey" PRIMARY KEY using index "reclamacoes_pkey";

alter table "public"."reservas" add constraint "reservas_pkey" PRIMARY KEY using index "reservas_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."visitantes" add constraint "visitantes_pkey" PRIMARY KEY using index "visitantes_pkey";

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_EM_PESSOAL_check" CHECK ((("EM_PESSOAL")::text ~~ '%@%'::text)) not valid;

alter table "public"."CSTB001_USER" validate constraint "CSTB001_USER_EM_PESSOAL_check";

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_EM_PESSOAL_key" UNIQUE using index "CSTB001_USER_EM_PESSOAL_key";

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_ID_CATEGORIA_ACESSO_fkey" FOREIGN KEY ("ID_CATEGORIA_ACESSO") REFERENCES public."CSTB010_CATEGORIA_ACESSO"("ID_CATEGORIA_ACESSO") not valid;

alter table "public"."CSTB001_USER" validate constraint "CSTB001_USER_ID_CATEGORIA_ACESSO_fkey";

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_NR_CPF_check" CHECK ((length(("NR_CPF")::text) = 11)) not valid;

alter table "public"."CSTB001_USER" validate constraint "CSTB001_USER_NR_CPF_check";

alter table "public"."CSTB001_USER" add constraint "CSTB001_USER_NR_CPF_key" UNIQUE using index "CSTB001_USER_NR_CPF_key";

alter table "public"."CSTB002_MORADOR" add constraint "CSTB002_MORADOR_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES public."CSTB001_USER"("ID_USER") ON DELETE CASCADE not valid;

alter table "public"."CSTB002_MORADOR" validate constraint "CSTB002_MORADOR_ID_USER_fkey";

alter table "public"."CSTB002_MORADOR" add constraint "CSTB002_MORADOR_ID_USER_key" UNIQUE using index "CSTB002_MORADOR_ID_USER_key";

alter table "public"."CSTB002_MORADOR" add constraint "CSTB002_MORADOR_NR_APARTAMENTO_check" CHECK (("NR_APARTAMENTO" > 0)) not valid;

alter table "public"."CSTB002_MORADOR" validate constraint "CSTB002_MORADOR_NR_APARTAMENTO_check";

alter table "public"."CSTB003_FUNCIONARIO" add constraint "CSTB003_FUNCIONARIO_ID_CATEGORIA_CARGO_fkey" FOREIGN KEY ("ID_CATEGORIA_CARGO") REFERENCES public."CSTB011_CATEGORIA_CARGO"("ID_CATEGORIA_CARGO") not valid;

alter table "public"."CSTB003_FUNCIONARIO" validate constraint "CSTB003_FUNCIONARIO_ID_CATEGORIA_CARGO_fkey";

alter table "public"."CSTB003_FUNCIONARIO" add constraint "CSTB003_FUNCIONARIO_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES public."CSTB001_USER"("ID_USER") ON DELETE CASCADE not valid;

alter table "public"."CSTB003_FUNCIONARIO" validate constraint "CSTB003_FUNCIONARIO_ID_USER_fkey";

alter table "public"."CSTB003_FUNCIONARIO" add constraint "CSTB003_FUNCIONARIO_ID_USER_key" UNIQUE using index "CSTB003_FUNCIONARIO_ID_USER_key";

alter table "public"."CSTB004_VISITANTE" add constraint "CSTB004_VISITANTE_NR_CPF_key" UNIQUE using index "CSTB004_VISITANTE_NR_CPF_key";

alter table "public"."CSTB004_VISITANTE" add constraint "CSTB004_VISITANTE_NR_RG_key" UNIQUE using index "CSTB004_VISITANTE_NR_RG_key";

alter table "public"."CSTB005_ENCOMENDA" add constraint "CSTB005_ENCOMENDA_ID_CATEGORIA_ENCOMENDA_fkey" FOREIGN KEY ("ID_CATEGORIA_ENCOMENDA") REFERENCES public."CSTB012_CATEGORIA_ENCOMENDA"("ID_CATEGORIA_ENCOMENDA") not valid;

alter table "public"."CSTB005_ENCOMENDA" validate constraint "CSTB005_ENCOMENDA_ID_CATEGORIA_ENCOMENDA_fkey";

alter table "public"."CSTB005_ENCOMENDA" add constraint "CSTB005_ENCOMENDA_ID_MORADOR_fkey" FOREIGN KEY ("ID_MORADOR") REFERENCES public."CSTB002_MORADOR"("ID_MORADOR") not valid;

alter table "public"."CSTB005_ENCOMENDA" validate constraint "CSTB005_ENCOMENDA_ID_MORADOR_fkey";

alter table "public"."CSTB008_LOCAL" add constraint "CSTB008_LOCAL_NO_LOCAL_key" UNIQUE using index "CSTB008_LOCAL_NO_LOCAL_key";

alter table "public"."CSTB009_RESERVA" add constraint "CSTB009_RESERVA_ID_CATEGORIA_RESERVA_fkey" FOREIGN KEY ("ID_CATEGORIA_RESERVA") REFERENCES public."CSTB014_CATEGORIA_RESERVA"("ID_CATEGORIA_RESERVA") not valid;

alter table "public"."CSTB009_RESERVA" validate constraint "CSTB009_RESERVA_ID_CATEGORIA_RESERVA_fkey";

alter table "public"."CSTB009_RESERVA" add constraint "CSTB009_RESERVA_ID_LOCAL_fkey" FOREIGN KEY ("ID_LOCAL") REFERENCES public."CSTB008_LOCAL"("ID_LOCAL") not valid;

alter table "public"."CSTB009_RESERVA" validate constraint "CSTB009_RESERVA_ID_LOCAL_fkey";

alter table "public"."CSTB015_ACESSO_VISITANTE" add constraint "CSTB015_ACESSO_VISITANTE_ID_FUNCIONARIO_fkey" FOREIGN KEY ("ID_FUNCIONARIO") REFERENCES public."CSTB003_FUNCIONARIO"("ID_FUNCIONARIO") not valid;

alter table "public"."CSTB015_ACESSO_VISITANTE" validate constraint "CSTB015_ACESSO_VISITANTE_ID_FUNCIONARIO_fkey";

alter table "public"."CSTB015_ACESSO_VISITANTE" add constraint "CSTB015_ACESSO_VISITANTE_ID_MORADOR_fkey" FOREIGN KEY ("ID_MORADOR") REFERENCES public."CSTB002_MORADOR"("ID_MORADOR") not valid;

alter table "public"."CSTB015_ACESSO_VISITANTE" validate constraint "CSTB015_ACESSO_VISITANTE_ID_MORADOR_fkey";

alter table "public"."CSTB015_ACESSO_VISITANTE" add constraint "CSTB015_ACESSO_VISITANTE_ID_VISITANTE_fkey" FOREIGN KEY ("ID_VISITANTE") REFERENCES public."CSTB004_VISITANTE"("ID_VISITANTE") not valid;

alter table "public"."CSTB015_ACESSO_VISITANTE" validate constraint "CSTB015_ACESSO_VISITANTE_ID_VISITANTE_fkey";

alter table "public"."CSTBH001_USER" add constraint "CSTBH001_USER_ID_USER_USUARIO_ACAO_REGISTRO_fkey" FOREIGN KEY ("ID_USER_USUARIO_ACAO_REGISTRO") REFERENCES public."CSTB001_USER"("ID_USER") ON DELETE CASCADE not valid;

alter table "public"."CSTBH001_USER" validate constraint "CSTBH001_USER_ID_USER_USUARIO_ACAO_REGISTRO_fkey";

alter table "public"."CSTBH002_MORADOR" add constraint "CSTBH002_MORADOR_ID_USER_AUDITOR_fkey" FOREIGN KEY ("ID_USER_AUDITOR") REFERENCES public."CSTB001_USER"("ID_USER") not valid;

alter table "public"."CSTBH002_MORADOR" validate constraint "CSTBH002_MORADOR_ID_USER_AUDITOR_fkey";

alter table "public"."CSTBH003_FUNCIONARIO" add constraint "CSTBH003_FUNCIONARIO_ID_USER_AUDITOR_fkey" FOREIGN KEY ("ID_USER_AUDITOR") REFERENCES public."CSTB001_USER"("ID_USER") not valid;

alter table "public"."CSTBH003_FUNCIONARIO" validate constraint "CSTBH003_FUNCIONARIO_ID_USER_AUDITOR_fkey";

alter table "public"."CSTBH005_ENCOMENDA" add constraint "CSTBH005_ENCOMENDA_ID_ENCOMENDA_fkey" FOREIGN KEY ("ID_ENCOMENDA") REFERENCES public."CSTB005_ENCOMENDA"("ID_ENCOMENDA") not valid;

alter table "public"."CSTBH005_ENCOMENDA" validate constraint "CSTBH005_ENCOMENDA_ID_ENCOMENDA_fkey";

alter table "public"."CSTBH005_ENCOMENDA" add constraint "CSTBH005_ENCOMENDA_ID_USER_AUDITOR_fkey" FOREIGN KEY ("ID_USER_AUDITOR") REFERENCES public."CSTB001_USER"("ID_USER") not valid;

alter table "public"."CSTBH005_ENCOMENDA" validate constraint "CSTBH005_ENCOMENDA_ID_USER_AUDITOR_fkey";

alter table "public"."CSTBH009_RESERVA" add constraint "CSTBH009_RESERVA_ID_RESERVA_fkey" FOREIGN KEY ("ID_RESERVA") REFERENCES public."CSTB009_RESERVA"("ID_RESERVA") not valid;

alter table "public"."CSTBH009_RESERVA" validate constraint "CSTBH009_RESERVA_ID_RESERVA_fkey";

alter table "public"."CSTBH009_RESERVA" add constraint "CSTBH009_RESERVA_ID_USER_AUDITOR_fkey" FOREIGN KEY ("ID_USER_AUDITOR") REFERENCES public."CSTB001_USER"("ID_USER") not valid;

alter table "public"."CSTBH009_RESERVA" validate constraint "CSTBH009_RESERVA_ID_USER_AUDITOR_fkey";

alter table "public"."encomendas" add constraint "fk31kn3bndvuum2d07beo42q9kd" FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) not valid;

alter table "public"."encomendas" validate constraint "fk31kn3bndvuum2d07beo42q9kd";

alter table "public"."encomendas" add constraint "fk6ki8pbrd66vtpt7xevq868q6g" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."encomendas" validate constraint "fk6ki8pbrd66vtpt7xevq868q6g";

alter table "public"."funcionarios" add constraint "fk7mf3shfr7b1j3cmxx1fh559vp" FOREIGN KEY (fk_user) REFERENCES public.users(id) not valid;

alter table "public"."funcionarios" validate constraint "fk7mf3shfr7b1j3cmxx1fh559vp";

alter table "public"."funcionarios" add constraint "uk6kjp10kpu332ce8dhlwwe2sin" UNIQUE using index "uk6kjp10kpu332ce8dhlwwe2sin";

alter table "public"."funcionarios" add constraint "uke0xb0ldevxbvutrllgobqfd1j" UNIQUE using index "uke0xb0ldevxbvutrllgobqfd1j";

alter table "public"."funcionarios" add constraint "uko60knm5wr28plxwo0clyg2eu4" UNIQUE using index "uko60knm5wr28plxwo0clyg2eu4";

alter table "public"."funcionarios" add constraint "ukrrykmyf711s2n7maopibw47s0" UNIQUE using index "ukrrykmyf711s2n7maopibw47s0";

alter table "public"."locais" add constraint "ukringk47bybtxxhm0aurt3c21q" UNIQUE using index "ukringk47bybtxxhm0aurt3c21q";

alter table "public"."moradores" add constraint "fkqr8u40httmaug4dd2knkdb697" FOREIGN KEY (fk_user) REFERENCES public.users(id) not valid;

alter table "public"."moradores" validate constraint "fkqr8u40httmaug4dd2knkdb697";

alter table "public"."moradores" add constraint "uk1pga1fiak1swwsqbxl328q2qr" UNIQUE using index "uk1pga1fiak1swwsqbxl328q2qr";

alter table "public"."moradores" add constraint "uk6ykj99wearulush38401ayk8t" UNIQUE using index "uk6ykj99wearulush38401ayk8t";

alter table "public"."moradores" add constraint "ukd5a73bi3k2ilof35177pvkrsk" UNIQUE using index "ukd5a73bi3k2ilof35177pvkrsk";

alter table "public"."moradores" add constraint "ukmqe8kkst1yn1vfejqtvdy3wcu" UNIQUE using index "ukmqe8kkst1yn1vfejqtvdy3wcu";

alter table "public"."reclamacoes" add constraint "fkb6wb7dhx4nry0qnjj87fq5bmm" FOREIGN KEY (fk_morador) REFERENCES public.moradores(id) not valid;

alter table "public"."reclamacoes" validate constraint "fkb6wb7dhx4nry0qnjj87fq5bmm";

alter table "public"."reclamacoes" add constraint "uk9eplb962yievbe8vq9n1t860s" UNIQUE using index "uk9eplb962yievbe8vq9n1t860s";

alter table "public"."reservas" add constraint "fkmlupau8oyqfgf4vaof15vq6l7" FOREIGN KEY (local_id) REFERENCES public.locais(id) not valid;

alter table "public"."reservas" validate constraint "fkmlupau8oyqfgf4vaof15vq6l7";

alter table "public"."reservas" add constraint "fks5wsc18biv3cqiq65ae0we280" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."reservas" validate constraint "fks5wsc18biv3cqiq65ae0we280";

alter table "public"."users" add constraint "uk7kqluf7wl0oxs7n90fpya03ss" UNIQUE using index "uk7kqluf7wl0oxs7n90fpya03ss";

alter table "public"."visitantes" add constraint "fkdpuwbgbhb26ccng43u9w08a30" FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id) not valid;

alter table "public"."visitantes" validate constraint "fkdpuwbgbhb26ccng43u9w08a30";

alter table "public"."visitantes" add constraint "fkl2vfmtc2icju76haimayangxc" FOREIGN KEY (morador_id) REFERENCES public.moradores(id) not valid;

alter table "public"."visitantes" validate constraint "fkl2vfmtc2icju76haimayangxc";

alter table "public"."visitantes" add constraint "uk7gfqyj9t2i54sy9q0a9dho856" UNIQUE using index "uk7gfqyj9t2i54sy9q0a9dho856";

alter table "public"."visitantes" add constraint "ukc481678h2nq80gfbwg0kk5f1f" UNIQUE using index "ukc481678h2nq80gfbwg0kk5f1f";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.csfn001_historico_usuario()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public."CSTBH001_USER" (
            "ID_USER", "NR_CPF", "NO_PESSOA", "NR_RG", "EM_PESSOAL", "NR_CELULAR", 
            "ID_CATEGORIA_ACESSO", "TX_SENHA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_USUARIO_ACAO_REGISTRO"
        )
        VALUES (
            OLD."ID_USER", OLD."NR_CPF", OLD."NO_PESSOA", OLD."NR_RG", OLD."EM_PESSOAL", nullif(OLD."NR_CELULAR", '')::numeric, 
            OLD."ID_CATEGORIA_ACESSO"::varchar, OLD."TX_SENHA", OLD."LG_ATIVO", 'D', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, OLD."ID_USER")
        );
        RETURN OLD;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public."CSTBH001_USER" (
            "ID_USER", "NR_CPF", "NO_PESSOA", "NR_RG", "EM_PESSOAL", "NR_CELULAR", 
            "ID_CATEGORIA_ACESSO", "TX_SENHA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_USUARIO_ACAO_REGISTRO"
        )
        VALUES (
            NEW."ID_USER", NEW."NR_CPF", NEW."NO_PESSOA", NEW."NR_RG", NEW."EM_PESSOAL", nullif(NEW."NR_CELULAR", '')::numeric, 
            NEW."ID_CATEGORIA_ACESSO"::varchar, NEW."TX_SENHA",NEW."LG_ATIVO", 'U', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public."CSTBH001_USER" (
            "ID_USER", "NR_CPF", "NO_PESSOA", "NR_RG", "EM_PESSOAL", "NR_CELULAR", 
            "ID_CATEGORIA_ACESSO", "TX_SENHA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_USUARIO_ACAO_REGISTRO"
        )
        VALUES (
            NEW."ID_USER", NEW."NR_CPF", NEW."NO_PESSOA", NEW."NR_RG", NEW."EM_PESSOAL", nullif(NEW."NR_CELULAR", '')::numeric, 
            NEW."ID_CATEGORIA_ACESSO"::varchar, NEW."TX_SENHA", NEW."LG_ATIVO", 'I', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.csfn002_historico_morador()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public."CSTBH002_MORADOR" (
            "ID_MORADOR", "ID_USER", "IC_BLOCO", "NR_APARTAMENTO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            OLD."ID_MORADOR", OLD."ID_USER", OLD."IC_BLOCO", OLD."NR_APARTAMENTO", 
            OLD."LG_ATIVO", 'D', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, OLD."ID_USER")
        );
        RETURN OLD;

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public."CSTBH002_MORADOR" (
            "ID_MORADOR", "ID_USER", "IC_BLOCO", "NR_APARTAMENTO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_MORADOR", NEW."ID_USER", NEW."IC_BLOCO", NEW."NR_APARTAMENTO", 
            NEW."LG_ATIVO", 'U', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;

    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public."CSTBH002_MORADOR" (
            "ID_MORADOR", "ID_USER", "IC_BLOCO", "NR_APARTAMENTO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_MORADOR", NEW."ID_USER", NEW."IC_BLOCO", NEW."NR_APARTAMENTO", 
            NEW."LG_ATIVO", 'I', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.csfn003_historico_funcionario()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public."CSTBH003_FUNCIONARIO" (
            "ID_FUNCIONARIO", "ID_USER", "ID_CATEGORIA_CARGO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            OLD."ID_FUNCIONARIO", OLD."ID_USER", OLD."ID_CATEGORIA_CARGO", 
            OLD."LG_ATIVO", 'D', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, OLD."ID_USER")
        );
        RETURN OLD;

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public."CSTBH003_FUNCIONARIO" (
            "ID_FUNCIONARIO", "ID_USER", "ID_CATEGORIA_CARGO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_FUNCIONARIO", NEW."ID_USER", NEW."ID_CATEGORIA_CARGO", 
            NEW."LG_ATIVO", 'U', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;

    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public."CSTBH003_FUNCIONARIO" (
            "ID_FUNCIONARIO", "ID_USER", "ID_CATEGORIA_CARGO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_FUNCIONARIO", NEW."ID_USER", NEW."ID_CATEGORIA_CARGO", 
            NEW."LG_ATIVO", 'I', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_USER")
        );
        RETURN NEW;
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.csfn004_historico_encomenda()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public."CSTBH005_ENCOMENDA" (
            "ID_ENCOMENDA", "ID_MORADOR", "ID_FUNCIONARIO", "NO_REMETENTE", 
            "ID_CATEGORIA_ENCOMENDA", "DT_RECEBIDO", "DT_RETIRADO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            OLD."ID_ENCOMENDA", OLD."ID_MORADOR", OLD."ID_FUNCIONARIO", OLD."NO_REMETENTE", 
            OLD."ID_CATEGORIA_ENCOMENDA", OLD."DT_RECEBIDO", OLD."DT_RETIRADO", 
            OLD."LG_ATIVO", 'D', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, OLD."ID_FUNCIONARIO")
        );
        RETURN OLD;

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public."CSTBH005_ENCOMENDA" (
            "ID_ENCOMENDA", "ID_MORADOR", "ID_FUNCIONARIO", "NO_REMETENTE", 
            "ID_CATEGORIA_ENCOMENDA", "DT_RECEBIDO", "DT_RETIRADO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_ENCOMENDA", NEW."ID_MORADOR", NEW."ID_FUNCIONARIO", NEW."NO_REMETENTE", 
            NEW."ID_CATEGORIA_ENCOMENDA", NEW."DT_RECEBIDO", NEW."DT_RETIRADO", 
            NEW."LG_ATIVO", 'U', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_FUNCIONARIO")
        );
        RETURN NEW;

    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public."CSTBH005_ENCOMENDA" (
            "ID_ENCOMENDA", "ID_MORADOR", "ID_FUNCIONARIO", "NO_REMETENTE", 
            "ID_CATEGORIA_ENCOMENDA", "DT_RECEBIDO", "DT_RETIRADO", 
            "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_ENCOMENDA", NEW."ID_MORADOR", NEW."ID_FUNCIONARIO", NEW."NO_REMETENTE", 
            NEW."ID_CATEGORIA_ENCOMENDA", NEW."DT_RECEBIDO", NEW."DT_RETIRADO", 
            NEW."LG_ATIVO", 'I', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_FUNCIONARIO")
        );
        RETURN NEW;
    END IF;
END;$function$
;

CREATE OR REPLACE FUNCTION public.csfn005_historico_reserva()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO public."CSTBH009_RESERVA" (
            "ID_RESERVA", "ID_MORADOR", "ID_LOCAL", "DT_INICIO", "DT_FIM", 
            "ID_CATEGORIA_RESERVA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            OLD."ID_RESERVA", OLD."ID_MORADOR", OLD."ID_LOCAL", OLD."DT_INICIO", OLD."DT_FIM", 
            OLD."ID_CATEGORIA_RESERVA", OLD."LG_ATIVO", 'D', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, OLD."ID_MORADOR")
        );
        RETURN OLD;

    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO public."CSTBH009_RESERVA" (
            "ID_RESERVA", "ID_MORADOR", "ID_LOCAL", "DT_INICIO", "DT_FIM", 
            "ID_CATEGORIA_RESERVA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_RESERVA", NEW."ID_MORADOR", NEW."ID_LOCAL", NEW."DT_INICIO", NEW."DT_FIM", 
            NEW."ID_CATEGORIA_RESERVA", NEW."LG_ATIVO", 'U', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_MORADOR")
        );
        RETURN NEW;

    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public."CSTBH009_RESERVA" (
            "ID_RESERVA", "ID_MORADOR", "ID_LOCAL", "DT_INICIO", "DT_FIM", 
            "ID_CATEGORIA_RESERVA", "LG_ATIVO", "IC_ACAO_REGISTRO", "ID_USER_AUDITOR"
        )
        VALUES (
            NEW."ID_RESERVA", NEW."ID_MORADOR", NEW."ID_LOCAL", NEW."DT_INICIO", NEW."DT_FIM", 
            NEW."ID_CATEGORIA_RESERVA", NEW."LG_ATIVO", 'I', 
            COALESCE(current_setting('app.current_user_id', true)::bigint, NEW."ID_MORADOR")
        );
        RETURN NEW;
    END IF;
END;
$function$
;

grant delete on table "public"."CSTB001_USER" to "anon";

grant insert on table "public"."CSTB001_USER" to "anon";

grant references on table "public"."CSTB001_USER" to "anon";

grant select on table "public"."CSTB001_USER" to "anon";

grant trigger on table "public"."CSTB001_USER" to "anon";

grant truncate on table "public"."CSTB001_USER" to "anon";

grant update on table "public"."CSTB001_USER" to "anon";

grant delete on table "public"."CSTB001_USER" to "authenticated";

grant insert on table "public"."CSTB001_USER" to "authenticated";

grant references on table "public"."CSTB001_USER" to "authenticated";

grant select on table "public"."CSTB001_USER" to "authenticated";

grant trigger on table "public"."CSTB001_USER" to "authenticated";

grant truncate on table "public"."CSTB001_USER" to "authenticated";

grant update on table "public"."CSTB001_USER" to "authenticated";

grant delete on table "public"."CSTB001_USER" to "service_role";

grant insert on table "public"."CSTB001_USER" to "service_role";

grant references on table "public"."CSTB001_USER" to "service_role";

grant select on table "public"."CSTB001_USER" to "service_role";

grant trigger on table "public"."CSTB001_USER" to "service_role";

grant truncate on table "public"."CSTB001_USER" to "service_role";

grant update on table "public"."CSTB001_USER" to "service_role";

grant delete on table "public"."CSTB002_MORADOR" to "anon";

grant insert on table "public"."CSTB002_MORADOR" to "anon";

grant references on table "public"."CSTB002_MORADOR" to "anon";

grant select on table "public"."CSTB002_MORADOR" to "anon";

grant trigger on table "public"."CSTB002_MORADOR" to "anon";

grant truncate on table "public"."CSTB002_MORADOR" to "anon";

grant update on table "public"."CSTB002_MORADOR" to "anon";

grant delete on table "public"."CSTB002_MORADOR" to "authenticated";

grant insert on table "public"."CSTB002_MORADOR" to "authenticated";

grant references on table "public"."CSTB002_MORADOR" to "authenticated";

grant select on table "public"."CSTB002_MORADOR" to "authenticated";

grant trigger on table "public"."CSTB002_MORADOR" to "authenticated";

grant truncate on table "public"."CSTB002_MORADOR" to "authenticated";

grant update on table "public"."CSTB002_MORADOR" to "authenticated";

grant delete on table "public"."CSTB002_MORADOR" to "service_role";

grant insert on table "public"."CSTB002_MORADOR" to "service_role";

grant references on table "public"."CSTB002_MORADOR" to "service_role";

grant select on table "public"."CSTB002_MORADOR" to "service_role";

grant trigger on table "public"."CSTB002_MORADOR" to "service_role";

grant truncate on table "public"."CSTB002_MORADOR" to "service_role";

grant update on table "public"."CSTB002_MORADOR" to "service_role";

grant delete on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant insert on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant references on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant select on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant trigger on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant truncate on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant update on table "public"."CSTB003_FUNCIONARIO" to "anon";

grant delete on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant insert on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant references on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant select on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant trigger on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant truncate on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant update on table "public"."CSTB003_FUNCIONARIO" to "authenticated";

grant delete on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant insert on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant references on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant select on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant trigger on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant truncate on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant update on table "public"."CSTB003_FUNCIONARIO" to "service_role";

grant delete on table "public"."CSTB004_VISITANTE" to "anon";

grant insert on table "public"."CSTB004_VISITANTE" to "anon";

grant references on table "public"."CSTB004_VISITANTE" to "anon";

grant select on table "public"."CSTB004_VISITANTE" to "anon";

grant trigger on table "public"."CSTB004_VISITANTE" to "anon";

grant truncate on table "public"."CSTB004_VISITANTE" to "anon";

grant update on table "public"."CSTB004_VISITANTE" to "anon";

grant delete on table "public"."CSTB004_VISITANTE" to "authenticated";

grant insert on table "public"."CSTB004_VISITANTE" to "authenticated";

grant references on table "public"."CSTB004_VISITANTE" to "authenticated";

grant select on table "public"."CSTB004_VISITANTE" to "authenticated";

grant trigger on table "public"."CSTB004_VISITANTE" to "authenticated";

grant truncate on table "public"."CSTB004_VISITANTE" to "authenticated";

grant update on table "public"."CSTB004_VISITANTE" to "authenticated";

grant delete on table "public"."CSTB004_VISITANTE" to "service_role";

grant insert on table "public"."CSTB004_VISITANTE" to "service_role";

grant references on table "public"."CSTB004_VISITANTE" to "service_role";

grant select on table "public"."CSTB004_VISITANTE" to "service_role";

grant trigger on table "public"."CSTB004_VISITANTE" to "service_role";

grant truncate on table "public"."CSTB004_VISITANTE" to "service_role";

grant update on table "public"."CSTB004_VISITANTE" to "service_role";

grant delete on table "public"."CSTB005_ENCOMENDA" to "anon";

grant insert on table "public"."CSTB005_ENCOMENDA" to "anon";

grant references on table "public"."CSTB005_ENCOMENDA" to "anon";

grant select on table "public"."CSTB005_ENCOMENDA" to "anon";

grant trigger on table "public"."CSTB005_ENCOMENDA" to "anon";

grant truncate on table "public"."CSTB005_ENCOMENDA" to "anon";

grant update on table "public"."CSTB005_ENCOMENDA" to "anon";

grant delete on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant insert on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant references on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant select on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant trigger on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant truncate on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant update on table "public"."CSTB005_ENCOMENDA" to "authenticated";

grant delete on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant insert on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant references on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant select on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant trigger on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant truncate on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant update on table "public"."CSTB005_ENCOMENDA" to "service_role";

grant delete on table "public"."CSTB006_RECLAMACAO" to "anon";

grant insert on table "public"."CSTB006_RECLAMACAO" to "anon";

grant references on table "public"."CSTB006_RECLAMACAO" to "anon";

grant select on table "public"."CSTB006_RECLAMACAO" to "anon";

grant trigger on table "public"."CSTB006_RECLAMACAO" to "anon";

grant truncate on table "public"."CSTB006_RECLAMACAO" to "anon";

grant update on table "public"."CSTB006_RECLAMACAO" to "anon";

grant delete on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant insert on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant references on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant select on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant trigger on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant truncate on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant update on table "public"."CSTB006_RECLAMACAO" to "authenticated";

grant delete on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant insert on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant references on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant select on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant trigger on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant truncate on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant update on table "public"."CSTB006_RECLAMACAO" to "service_role";

grant delete on table "public"."CSTB007_AVISO" to "anon";

grant insert on table "public"."CSTB007_AVISO" to "anon";

grant references on table "public"."CSTB007_AVISO" to "anon";

grant select on table "public"."CSTB007_AVISO" to "anon";

grant trigger on table "public"."CSTB007_AVISO" to "anon";

grant truncate on table "public"."CSTB007_AVISO" to "anon";

grant update on table "public"."CSTB007_AVISO" to "anon";

grant delete on table "public"."CSTB007_AVISO" to "authenticated";

grant insert on table "public"."CSTB007_AVISO" to "authenticated";

grant references on table "public"."CSTB007_AVISO" to "authenticated";

grant select on table "public"."CSTB007_AVISO" to "authenticated";

grant trigger on table "public"."CSTB007_AVISO" to "authenticated";

grant truncate on table "public"."CSTB007_AVISO" to "authenticated";

grant update on table "public"."CSTB007_AVISO" to "authenticated";

grant delete on table "public"."CSTB007_AVISO" to "service_role";

grant insert on table "public"."CSTB007_AVISO" to "service_role";

grant references on table "public"."CSTB007_AVISO" to "service_role";

grant select on table "public"."CSTB007_AVISO" to "service_role";

grant trigger on table "public"."CSTB007_AVISO" to "service_role";

grant truncate on table "public"."CSTB007_AVISO" to "service_role";

grant update on table "public"."CSTB007_AVISO" to "service_role";

grant delete on table "public"."CSTB008_LOCAL" to "anon";

grant insert on table "public"."CSTB008_LOCAL" to "anon";

grant references on table "public"."CSTB008_LOCAL" to "anon";

grant select on table "public"."CSTB008_LOCAL" to "anon";

grant trigger on table "public"."CSTB008_LOCAL" to "anon";

grant truncate on table "public"."CSTB008_LOCAL" to "anon";

grant update on table "public"."CSTB008_LOCAL" to "anon";

grant delete on table "public"."CSTB008_LOCAL" to "authenticated";

grant insert on table "public"."CSTB008_LOCAL" to "authenticated";

grant references on table "public"."CSTB008_LOCAL" to "authenticated";

grant select on table "public"."CSTB008_LOCAL" to "authenticated";

grant trigger on table "public"."CSTB008_LOCAL" to "authenticated";

grant truncate on table "public"."CSTB008_LOCAL" to "authenticated";

grant update on table "public"."CSTB008_LOCAL" to "authenticated";

grant delete on table "public"."CSTB008_LOCAL" to "service_role";

grant insert on table "public"."CSTB008_LOCAL" to "service_role";

grant references on table "public"."CSTB008_LOCAL" to "service_role";

grant select on table "public"."CSTB008_LOCAL" to "service_role";

grant trigger on table "public"."CSTB008_LOCAL" to "service_role";

grant truncate on table "public"."CSTB008_LOCAL" to "service_role";

grant update on table "public"."CSTB008_LOCAL" to "service_role";

grant delete on table "public"."CSTB009_RESERVA" to "anon";

grant insert on table "public"."CSTB009_RESERVA" to "anon";

grant references on table "public"."CSTB009_RESERVA" to "anon";

grant select on table "public"."CSTB009_RESERVA" to "anon";

grant trigger on table "public"."CSTB009_RESERVA" to "anon";

grant truncate on table "public"."CSTB009_RESERVA" to "anon";

grant update on table "public"."CSTB009_RESERVA" to "anon";

grant delete on table "public"."CSTB009_RESERVA" to "authenticated";

grant insert on table "public"."CSTB009_RESERVA" to "authenticated";

grant references on table "public"."CSTB009_RESERVA" to "authenticated";

grant select on table "public"."CSTB009_RESERVA" to "authenticated";

grant trigger on table "public"."CSTB009_RESERVA" to "authenticated";

grant truncate on table "public"."CSTB009_RESERVA" to "authenticated";

grant update on table "public"."CSTB009_RESERVA" to "authenticated";

grant delete on table "public"."CSTB009_RESERVA" to "service_role";

grant insert on table "public"."CSTB009_RESERVA" to "service_role";

grant references on table "public"."CSTB009_RESERVA" to "service_role";

grant select on table "public"."CSTB009_RESERVA" to "service_role";

grant trigger on table "public"."CSTB009_RESERVA" to "service_role";

grant truncate on table "public"."CSTB009_RESERVA" to "service_role";

grant update on table "public"."CSTB009_RESERVA" to "service_role";

grant delete on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant insert on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant references on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant select on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant trigger on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant truncate on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant update on table "public"."CSTB010_CATEGORIA_ACESSO" to "anon";

grant delete on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant insert on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant references on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant select on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant trigger on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant truncate on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant update on table "public"."CSTB010_CATEGORIA_ACESSO" to "authenticated";

grant delete on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant insert on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant references on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant select on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant trigger on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant truncate on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant update on table "public"."CSTB010_CATEGORIA_ACESSO" to "service_role";

grant delete on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant insert on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant references on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant select on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant trigger on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant truncate on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant update on table "public"."CSTB011_CATEGORIA_CARGO" to "anon";

grant delete on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant insert on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant references on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant select on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant trigger on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant truncate on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant update on table "public"."CSTB011_CATEGORIA_CARGO" to "authenticated";

grant delete on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant insert on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant references on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant select on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant trigger on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant truncate on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant update on table "public"."CSTB011_CATEGORIA_CARGO" to "service_role";

grant delete on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant insert on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant references on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant select on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant trigger on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant truncate on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant update on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "anon";

grant delete on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant insert on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant references on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant select on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant trigger on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant truncate on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant update on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "authenticated";

grant delete on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant insert on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant references on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant select on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant trigger on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant truncate on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant update on table "public"."CSTB012_CATEGORIA_ENCOMENDA" to "service_role";

grant delete on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant insert on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant references on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant select on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant trigger on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant truncate on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant update on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "anon";

grant delete on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant insert on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant references on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant select on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant trigger on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant truncate on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant update on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "authenticated";

grant delete on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant insert on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant references on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant select on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant trigger on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant truncate on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant update on table "public"."CSTB013_CATEGORIA_RECLAMACAO" to "service_role";

grant delete on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant insert on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant references on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant select on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant trigger on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant truncate on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant update on table "public"."CSTB014_CATEGORIA_RESERVA" to "anon";

grant delete on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant insert on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant references on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant select on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant trigger on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant truncate on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant update on table "public"."CSTB014_CATEGORIA_RESERVA" to "authenticated";

grant delete on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant insert on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant references on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant select on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant trigger on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant truncate on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant update on table "public"."CSTB014_CATEGORIA_RESERVA" to "service_role";

grant delete on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant insert on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant references on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant select on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant trigger on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant truncate on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant update on table "public"."CSTB015_ACESSO_VISITANTE" to "anon";

grant delete on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant insert on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant references on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant select on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant trigger on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant truncate on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant update on table "public"."CSTB015_ACESSO_VISITANTE" to "authenticated";

grant delete on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant insert on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant references on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant select on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant trigger on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant truncate on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant update on table "public"."CSTB015_ACESSO_VISITANTE" to "service_role";

grant delete on table "public"."CSTBH001_USER" to "anon";

grant insert on table "public"."CSTBH001_USER" to "anon";

grant references on table "public"."CSTBH001_USER" to "anon";

grant select on table "public"."CSTBH001_USER" to "anon";

grant trigger on table "public"."CSTBH001_USER" to "anon";

grant truncate on table "public"."CSTBH001_USER" to "anon";

grant update on table "public"."CSTBH001_USER" to "anon";

grant delete on table "public"."CSTBH001_USER" to "authenticated";

grant insert on table "public"."CSTBH001_USER" to "authenticated";

grant references on table "public"."CSTBH001_USER" to "authenticated";

grant select on table "public"."CSTBH001_USER" to "authenticated";

grant trigger on table "public"."CSTBH001_USER" to "authenticated";

grant truncate on table "public"."CSTBH001_USER" to "authenticated";

grant update on table "public"."CSTBH001_USER" to "authenticated";

grant delete on table "public"."CSTBH001_USER" to "service_role";

grant insert on table "public"."CSTBH001_USER" to "service_role";

grant references on table "public"."CSTBH001_USER" to "service_role";

grant select on table "public"."CSTBH001_USER" to "service_role";

grant trigger on table "public"."CSTBH001_USER" to "service_role";

grant truncate on table "public"."CSTBH001_USER" to "service_role";

grant update on table "public"."CSTBH001_USER" to "service_role";

grant delete on table "public"."CSTBH002_MORADOR" to "anon";

grant insert on table "public"."CSTBH002_MORADOR" to "anon";

grant references on table "public"."CSTBH002_MORADOR" to "anon";

grant select on table "public"."CSTBH002_MORADOR" to "anon";

grant trigger on table "public"."CSTBH002_MORADOR" to "anon";

grant truncate on table "public"."CSTBH002_MORADOR" to "anon";

grant update on table "public"."CSTBH002_MORADOR" to "anon";

grant delete on table "public"."CSTBH002_MORADOR" to "authenticated";

grant insert on table "public"."CSTBH002_MORADOR" to "authenticated";

grant references on table "public"."CSTBH002_MORADOR" to "authenticated";

grant select on table "public"."CSTBH002_MORADOR" to "authenticated";

grant trigger on table "public"."CSTBH002_MORADOR" to "authenticated";

grant truncate on table "public"."CSTBH002_MORADOR" to "authenticated";

grant update on table "public"."CSTBH002_MORADOR" to "authenticated";

grant delete on table "public"."CSTBH002_MORADOR" to "service_role";

grant insert on table "public"."CSTBH002_MORADOR" to "service_role";

grant references on table "public"."CSTBH002_MORADOR" to "service_role";

grant select on table "public"."CSTBH002_MORADOR" to "service_role";

grant trigger on table "public"."CSTBH002_MORADOR" to "service_role";

grant truncate on table "public"."CSTBH002_MORADOR" to "service_role";

grant update on table "public"."CSTBH002_MORADOR" to "service_role";

grant delete on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant insert on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant references on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant select on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant trigger on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant truncate on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant update on table "public"."CSTBH003_FUNCIONARIO" to "anon";

grant delete on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant insert on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant references on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant select on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant trigger on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant truncate on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant update on table "public"."CSTBH003_FUNCIONARIO" to "authenticated";

grant delete on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant insert on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant references on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant select on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant trigger on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant truncate on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant update on table "public"."CSTBH003_FUNCIONARIO" to "service_role";

grant delete on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant insert on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant references on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant select on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant trigger on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant truncate on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant update on table "public"."CSTBH005_ENCOMENDA" to "anon";

grant delete on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant insert on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant references on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant select on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant trigger on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant truncate on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant update on table "public"."CSTBH005_ENCOMENDA" to "authenticated";

grant delete on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant insert on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant references on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant select on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant trigger on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant truncate on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant update on table "public"."CSTBH005_ENCOMENDA" to "service_role";

grant delete on table "public"."CSTBH009_RESERVA" to "anon";

grant insert on table "public"."CSTBH009_RESERVA" to "anon";

grant references on table "public"."CSTBH009_RESERVA" to "anon";

grant select on table "public"."CSTBH009_RESERVA" to "anon";

grant trigger on table "public"."CSTBH009_RESERVA" to "anon";

grant truncate on table "public"."CSTBH009_RESERVA" to "anon";

grant update on table "public"."CSTBH009_RESERVA" to "anon";

grant delete on table "public"."CSTBH009_RESERVA" to "authenticated";

grant insert on table "public"."CSTBH009_RESERVA" to "authenticated";

grant references on table "public"."CSTBH009_RESERVA" to "authenticated";

grant select on table "public"."CSTBH009_RESERVA" to "authenticated";

grant trigger on table "public"."CSTBH009_RESERVA" to "authenticated";

grant truncate on table "public"."CSTBH009_RESERVA" to "authenticated";

grant update on table "public"."CSTBH009_RESERVA" to "authenticated";

grant delete on table "public"."CSTBH009_RESERVA" to "service_role";

grant insert on table "public"."CSTBH009_RESERVA" to "service_role";

grant references on table "public"."CSTBH009_RESERVA" to "service_role";

grant select on table "public"."CSTBH009_RESERVA" to "service_role";

grant trigger on table "public"."CSTBH009_RESERVA" to "service_role";

grant truncate on table "public"."CSTBH009_RESERVA" to "service_role";

grant update on table "public"."CSTBH009_RESERVA" to "service_role";

grant delete on table "public"."avisos" to "anon";

grant insert on table "public"."avisos" to "anon";

grant references on table "public"."avisos" to "anon";

grant select on table "public"."avisos" to "anon";

grant trigger on table "public"."avisos" to "anon";

grant truncate on table "public"."avisos" to "anon";

grant update on table "public"."avisos" to "anon";

grant delete on table "public"."avisos" to "authenticated";

grant insert on table "public"."avisos" to "authenticated";

grant references on table "public"."avisos" to "authenticated";

grant select on table "public"."avisos" to "authenticated";

grant trigger on table "public"."avisos" to "authenticated";

grant truncate on table "public"."avisos" to "authenticated";

grant update on table "public"."avisos" to "authenticated";

grant delete on table "public"."avisos" to "service_role";

grant insert on table "public"."avisos" to "service_role";

grant references on table "public"."avisos" to "service_role";

grant select on table "public"."avisos" to "service_role";

grant trigger on table "public"."avisos" to "service_role";

grant truncate on table "public"."avisos" to "service_role";

grant update on table "public"."avisos" to "service_role";

grant delete on table "public"."encomendas" to "anon";

grant insert on table "public"."encomendas" to "anon";

grant references on table "public"."encomendas" to "anon";

grant select on table "public"."encomendas" to "anon";

grant trigger on table "public"."encomendas" to "anon";

grant truncate on table "public"."encomendas" to "anon";

grant update on table "public"."encomendas" to "anon";

grant delete on table "public"."encomendas" to "authenticated";

grant insert on table "public"."encomendas" to "authenticated";

grant references on table "public"."encomendas" to "authenticated";

grant select on table "public"."encomendas" to "authenticated";

grant trigger on table "public"."encomendas" to "authenticated";

grant truncate on table "public"."encomendas" to "authenticated";

grant update on table "public"."encomendas" to "authenticated";

grant delete on table "public"."encomendas" to "service_role";

grant insert on table "public"."encomendas" to "service_role";

grant references on table "public"."encomendas" to "service_role";

grant select on table "public"."encomendas" to "service_role";

grant trigger on table "public"."encomendas" to "service_role";

grant truncate on table "public"."encomendas" to "service_role";

grant update on table "public"."encomendas" to "service_role";

grant delete on table "public"."funcionarios" to "anon";

grant insert on table "public"."funcionarios" to "anon";

grant references on table "public"."funcionarios" to "anon";

grant select on table "public"."funcionarios" to "anon";

grant trigger on table "public"."funcionarios" to "anon";

grant truncate on table "public"."funcionarios" to "anon";

grant update on table "public"."funcionarios" to "anon";

grant delete on table "public"."funcionarios" to "authenticated";

grant insert on table "public"."funcionarios" to "authenticated";

grant references on table "public"."funcionarios" to "authenticated";

grant select on table "public"."funcionarios" to "authenticated";

grant trigger on table "public"."funcionarios" to "authenticated";

grant truncate on table "public"."funcionarios" to "authenticated";

grant update on table "public"."funcionarios" to "authenticated";

grant delete on table "public"."funcionarios" to "service_role";

grant insert on table "public"."funcionarios" to "service_role";

grant references on table "public"."funcionarios" to "service_role";

grant select on table "public"."funcionarios" to "service_role";

grant trigger on table "public"."funcionarios" to "service_role";

grant truncate on table "public"."funcionarios" to "service_role";

grant update on table "public"."funcionarios" to "service_role";

grant delete on table "public"."locais" to "anon";

grant insert on table "public"."locais" to "anon";

grant references on table "public"."locais" to "anon";

grant select on table "public"."locais" to "anon";

grant trigger on table "public"."locais" to "anon";

grant truncate on table "public"."locais" to "anon";

grant update on table "public"."locais" to "anon";

grant delete on table "public"."locais" to "authenticated";

grant insert on table "public"."locais" to "authenticated";

grant references on table "public"."locais" to "authenticated";

grant select on table "public"."locais" to "authenticated";

grant trigger on table "public"."locais" to "authenticated";

grant truncate on table "public"."locais" to "authenticated";

grant update on table "public"."locais" to "authenticated";

grant delete on table "public"."locais" to "service_role";

grant insert on table "public"."locais" to "service_role";

grant references on table "public"."locais" to "service_role";

grant select on table "public"."locais" to "service_role";

grant trigger on table "public"."locais" to "service_role";

grant truncate on table "public"."locais" to "service_role";

grant update on table "public"."locais" to "service_role";

grant delete on table "public"."moradores" to "anon";

grant insert on table "public"."moradores" to "anon";

grant references on table "public"."moradores" to "anon";

grant select on table "public"."moradores" to "anon";

grant trigger on table "public"."moradores" to "anon";

grant truncate on table "public"."moradores" to "anon";

grant update on table "public"."moradores" to "anon";

grant delete on table "public"."moradores" to "authenticated";

grant insert on table "public"."moradores" to "authenticated";

grant references on table "public"."moradores" to "authenticated";

grant select on table "public"."moradores" to "authenticated";

grant trigger on table "public"."moradores" to "authenticated";

grant truncate on table "public"."moradores" to "authenticated";

grant update on table "public"."moradores" to "authenticated";

grant delete on table "public"."moradores" to "service_role";

grant insert on table "public"."moradores" to "service_role";

grant references on table "public"."moradores" to "service_role";

grant select on table "public"."moradores" to "service_role";

grant trigger on table "public"."moradores" to "service_role";

grant truncate on table "public"."moradores" to "service_role";

grant update on table "public"."moradores" to "service_role";

grant delete on table "public"."reclamacoes" to "anon";

grant insert on table "public"."reclamacoes" to "anon";

grant references on table "public"."reclamacoes" to "anon";

grant select on table "public"."reclamacoes" to "anon";

grant trigger on table "public"."reclamacoes" to "anon";

grant truncate on table "public"."reclamacoes" to "anon";

grant update on table "public"."reclamacoes" to "anon";

grant delete on table "public"."reclamacoes" to "authenticated";

grant insert on table "public"."reclamacoes" to "authenticated";

grant references on table "public"."reclamacoes" to "authenticated";

grant select on table "public"."reclamacoes" to "authenticated";

grant trigger on table "public"."reclamacoes" to "authenticated";

grant truncate on table "public"."reclamacoes" to "authenticated";

grant update on table "public"."reclamacoes" to "authenticated";

grant delete on table "public"."reclamacoes" to "service_role";

grant insert on table "public"."reclamacoes" to "service_role";

grant references on table "public"."reclamacoes" to "service_role";

grant select on table "public"."reclamacoes" to "service_role";

grant trigger on table "public"."reclamacoes" to "service_role";

grant truncate on table "public"."reclamacoes" to "service_role";

grant update on table "public"."reclamacoes" to "service_role";

grant delete on table "public"."reservas" to "anon";

grant insert on table "public"."reservas" to "anon";

grant references on table "public"."reservas" to "anon";

grant select on table "public"."reservas" to "anon";

grant trigger on table "public"."reservas" to "anon";

grant truncate on table "public"."reservas" to "anon";

grant update on table "public"."reservas" to "anon";

grant delete on table "public"."reservas" to "authenticated";

grant insert on table "public"."reservas" to "authenticated";

grant references on table "public"."reservas" to "authenticated";

grant select on table "public"."reservas" to "authenticated";

grant trigger on table "public"."reservas" to "authenticated";

grant truncate on table "public"."reservas" to "authenticated";

grant update on table "public"."reservas" to "authenticated";

grant delete on table "public"."reservas" to "service_role";

grant insert on table "public"."reservas" to "service_role";

grant references on table "public"."reservas" to "service_role";

grant select on table "public"."reservas" to "service_role";

grant trigger on table "public"."reservas" to "service_role";

grant truncate on table "public"."reservas" to "service_role";

grant update on table "public"."reservas" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."visitantes" to "anon";

grant insert on table "public"."visitantes" to "anon";

grant references on table "public"."visitantes" to "anon";

grant select on table "public"."visitantes" to "anon";

grant trigger on table "public"."visitantes" to "anon";

grant truncate on table "public"."visitantes" to "anon";

grant update on table "public"."visitantes" to "anon";

grant delete on table "public"."visitantes" to "authenticated";

grant insert on table "public"."visitantes" to "authenticated";

grant references on table "public"."visitantes" to "authenticated";

grant select on table "public"."visitantes" to "authenticated";

grant trigger on table "public"."visitantes" to "authenticated";

grant truncate on table "public"."visitantes" to "authenticated";

grant update on table "public"."visitantes" to "authenticated";

grant delete on table "public"."visitantes" to "service_role";

grant insert on table "public"."visitantes" to "service_role";

grant references on table "public"."visitantes" to "service_role";

grant select on table "public"."visitantes" to "service_role";

grant trigger on table "public"."visitantes" to "service_role";

grant truncate on table "public"."visitantes" to "service_role";

grant update on table "public"."visitantes" to "service_role";

CREATE TRIGGER tr01_cstb001 AFTER INSERT OR DELETE OR UPDATE ON public."CSTB001_USER" FOR EACH ROW EXECUTE FUNCTION public.csfn001_historico_usuario();

CREATE TRIGGER tr02_cstb002 AFTER INSERT OR DELETE OR UPDATE ON public."CSTB002_MORADOR" FOR EACH ROW EXECUTE FUNCTION public.csfn002_historico_morador();

CREATE TRIGGER tr03_cstb003 AFTER INSERT OR DELETE OR UPDATE ON public."CSTB003_FUNCIONARIO" FOR EACH ROW EXECUTE FUNCTION public.csfn003_historico_funcionario();

CREATE TRIGGER tr04_cstb005 AFTER INSERT OR DELETE OR UPDATE ON public."CSTB005_ENCOMENDA" FOR EACH ROW EXECUTE FUNCTION public.csfn004_historico_encomenda();

CREATE TRIGGER tr05_cstb009 AFTER INSERT OR DELETE OR UPDATE ON public."CSTB009_RESERVA" FOR EACH ROW EXECUTE FUNCTION public.csfn005_historico_reserva();


