version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      SPRING_DATASOURCE_USERNAME: postgres.vuytwwmyafbaubeoapcj
      SPRING_DATASOURCE_PASSWORD: condosync
      SERVER_PORT: 8080
    # Iniciar o back-end em dev
    command: ./gradlew bootRun

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Volume anônimo para evitar conflitos de dependências
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    # Iniciar o servidor de desenvolvimento
    command: npm run dev -- --host