services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: condosync_rabbitmq
    ports:
      - "5672:5672"   # Comunicação interna/AMQP
      - "15672:15672" # Painel Web (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  backend:
    build:
      context: ./backend_novo  # Caminho para sua pasta .NET
      dockerfile: Dockerfile   # Certifique-se de ter um Dockerfile para .NET
    container_name: condosync_api
    ports:
      - "${PORT_BACKEND}:8080" # Mapeia a porta configurada para a 8080 interna do container
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__Port=${RABBITMQ_PORT}
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: condosync_web
    ports:
      - "${PORT_FRONTEND}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:${PORT_BACKEND}/api
    command: npm run dev -- --host