-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.CSTB001_USER (
  ID_USER bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NR_CPF character varying NOT NULL UNIQUE CHECK (length("NR_CPF"::text) = 11),
  NO_PESSOA character varying NOT NULL,
  NR_RG character varying UNIQUE,
  EM_PESSOAL character varying NOT NULL UNIQUE CHECK ("EM_PESSOAL"::text ~~ '%@%'::text),
  NR_CELULAR character varying,
  ID_CATEGORIA_ACESSO bigint NOT NULL,
  TX_SENHA character varying NOT NULL,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB001_USER_pkey PRIMARY KEY (ID_USER),
  CONSTRAINT CSTB001_USER_ID_CATEGORIA_ACESSO_fkey FOREIGN KEY (ID_CATEGORIA_ACESSO) REFERENCES public.CSTB010_CATEGORIA_ACESSO(ID_CATEGORIA_ACESSO)
);
CREATE TABLE public.CSTB002_MORADOR (
  ID_MORADOR bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_USER bigint NOT NULL UNIQUE,
  IC_BLOCO character varying NOT NULL,
  NR_APARTAMENTO integer NOT NULL CHECK ("NR_APARTAMENTO" > 0),
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB002_MORADOR_pkey PRIMARY KEY (ID_MORADOR),
  CONSTRAINT CSTB002_MORADOR_ID_USER_fkey FOREIGN KEY (ID_USER) REFERENCES public.CSTB001_USER(ID_USER)
);
CREATE TABLE public.CSTB003_FUNCIONARIO (
  ID_FUNCIONARIO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_USER bigint NOT NULL UNIQUE,
  ID_CATEGORIA_CARGO bigint NOT NULL,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB003_FUNCIONARIO_pkey PRIMARY KEY (ID_FUNCIONARIO),
  CONSTRAINT CSTB003_FUNCIONARIO_ID_USER_fkey FOREIGN KEY (ID_USER) REFERENCES public.CSTB001_USER(ID_USER),
  CONSTRAINT CSTB003_FUNCIONARIO_ID_CATEGORIA_CARGO_fkey FOREIGN KEY (ID_CATEGORIA_CARGO) REFERENCES public.CSTB011_CATEGORIA_CARGO(ID_CATEGORIA_CARGO)
);
CREATE TABLE public.CSTB004_VISITANTE (
  ID_VISITANTE bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_PESSOA character varying NOT NULL,
  NR_CPF character varying UNIQUE,
  NR_RG character varying NOT NULL UNIQUE,
  NR_TELEFONE character varying,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB004_VISITANTE_pkey PRIMARY KEY (ID_VISITANTE)
);
CREATE TABLE public.CSTB005_ENCOMENDA (
  ID_ENCOMENDA bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_MORADOR bigint NOT NULL,
  ID_FUNCIONARIO bigint NOT NULL,
  NO_REMETENTE character varying NOT NULL,
  ID_CATEGORIA_ENCOMENDA bigint NOT NULL,
  DT_RECEBIDO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_RETIRADO timestamp without time zone,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB005_ENCOMENDA_pkey PRIMARY KEY (ID_ENCOMENDA),
  CONSTRAINT CSTB005_ENCOMENDA_ID_MORADOR_fkey FOREIGN KEY (ID_MORADOR) REFERENCES public.CSTB002_MORADOR(ID_MORADOR),
  CONSTRAINT CSTB005_ENCOMENDA_ID_CATEGORIA_ENCOMENDA_fkey FOREIGN KEY (ID_CATEGORIA_ENCOMENDA) REFERENCES public.CSTB012_CATEGORIA_ENCOMENDA(ID_CATEGORIA_ENCOMENDA)
);
CREATE TABLE public.CSTB006_RECLAMACAO (
  ID_RECLAMACAO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_MORADOR bigint NOT NULL,
  TX_TITULO character varying NOT NULL,
  DS_RECLAMACAO text NOT NULL,
  ID_CATEGORIA_RECLAMACAO bigint NOT NULL,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB006_RECLAMACAO_pkey PRIMARY KEY (ID_RECLAMACAO)
);
CREATE TABLE public.CSTB007_AVISO (
  ID_AVISO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_USER bigint NOT NULL,
  TX_TITULO character varying NOT NULL,
  DS_AVISO text NOT NULL,
  DT_EXPIRACAO timestamp without time zone,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB007_AVISO_pkey PRIMARY KEY (ID_AVISO)
);
CREATE TABLE public.CSTB008_LOCAL (
  ID_LOCAL bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_LOCAL character varying NOT NULL UNIQUE,
  NR_CAPACIDADE integer NOT NULL,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB008_LOCAL_pkey PRIMARY KEY (ID_LOCAL)
);
CREATE TABLE public.CSTB009_RESERVA (
  ID_RESERVA bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_MORADOR bigint NOT NULL,
  ID_LOCAL bigint NOT NULL,
  DT_INICIO timestamp without time zone NOT NULL,
  DT_FIM timestamp without time zone NOT NULL,
  ID_CATEGORIA_RESERVA bigint NOT NULL,
  LG_ATIVO boolean NOT NULL DEFAULT true,
  CONSTRAINT CSTB009_RESERVA_pkey PRIMARY KEY (ID_RESERVA),
  CONSTRAINT CSTB009_RESERVA_ID_LOCAL_fkey FOREIGN KEY (ID_LOCAL) REFERENCES public.CSTB008_LOCAL(ID_LOCAL),
  CONSTRAINT CSTB009_RESERVA_ID_CATEGORIA_RESERVA_fkey FOREIGN KEY (ID_CATEGORIA_RESERVA) REFERENCES public.CSTB014_CATEGORIA_RESERVA(ID_CATEGORIA_RESERVA)
);
CREATE TABLE public.CSTB010_CATEGORIA_ACESSO (
  ID_CATEGORIA_ACESSO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_CATEGORIA_ACESSO character varying NOT NULL,
  CONSTRAINT CSTB010_CATEGORIA_ACESSO_pkey PRIMARY KEY (ID_CATEGORIA_ACESSO)
);
CREATE TABLE public.CSTB011_CATEGORIA_CARGO (
  ID_CATEGORIA_CARGO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_CATEGORIA_CARGO character varying NOT NULL,
  CONSTRAINT CSTB011_CATEGORIA_CARGO_pkey PRIMARY KEY (ID_CATEGORIA_CARGO)
);
CREATE TABLE public.CSTB012_CATEGORIA_ENCOMENDA (
  ID_CATEGORIA_ENCOMENDA bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_CATEGORIA_ENCOMENDA character varying NOT NULL,
  CONSTRAINT CSTB012_CATEGORIA_ENCOMENDA_pkey PRIMARY KEY (ID_CATEGORIA_ENCOMENDA)
);
CREATE TABLE public.CSTB013_CATEGORIA_RECLAMACAO (
  ID_CATEGORIA_RECLAMACAO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_CATEGORIA_RECLAMACAO character varying NOT NULL DEFAULT 'ABERTA'::character varying,
  CONSTRAINT CSTB013_CATEGORIA_RECLAMACAO_pkey PRIMARY KEY (ID_CATEGORIA_RECLAMACAO)
);
CREATE TABLE public.CSTB014_CATEGORIA_RESERVA (
  ID_CATEGORIA_RESERVA bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NO_CATEGORIA_RESERVA character varying NOT NULL DEFAULT 'CONFIRMADA'::character varying,
  CONSTRAINT CSTB014_CATEGORIA_RESERVA_pkey PRIMARY KEY (ID_CATEGORIA_RESERVA)
);
CREATE TABLE public.CSTB015_ACESSO_VISITANTE (
  ID_ACESSO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_VISITANTE bigint NOT NULL,
  ID_MORADOR bigint NOT NULL,
  ID_FUNCIONARIO bigint NOT NULL,
  DT_ENTRADA timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_SAIDA timestamp without time zone,
  CONSTRAINT CSTB015_ACESSO_VISITANTE_pkey PRIMARY KEY (ID_ACESSO),
  CONSTRAINT CSTB015_ACESSO_VISITANTE_ID_VISITANTE_fkey FOREIGN KEY (ID_VISITANTE) REFERENCES public.CSTB004_VISITANTE(ID_VISITANTE),
  CONSTRAINT CSTB015_ACESSO_VISITANTE_ID_MORADOR_fkey FOREIGN KEY (ID_MORADOR) REFERENCES public.CSTB002_MORADOR(ID_MORADOR),
  CONSTRAINT CSTB015_ACESSO_VISITANTE_ID_FUNCIONARIO_fkey FOREIGN KEY (ID_FUNCIONARIO) REFERENCES public.CSTB003_FUNCIONARIO(ID_FUNCIONARIO)
);
CREATE TABLE public.CSTBH001_USER (
  ID_HISTORICO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_USER bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  NR_CPF character varying NOT NULL UNIQUE,
  NO_PESSOA character varying NOT NULL,
  NR_RG character varying UNIQUE,
  EM_PESSOAL character varying NOT NULL UNIQUE,
  NR_CELULAR numeric,
  ID_CATEGORIA_ACESSO character varying NOT NULL,
  TX_SENHA character varying NOT NULL,
  IC_ATIVO character NOT NULL DEFAULT 'S'::bpchar,
  DH_ACAO_REGISTRO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IC_ACAO_REGISTRO character NOT NULL,
  ID_USER_USUARIO_ACAO_REGISTRO bigint NOT NULL,
  CONSTRAINT CSTBH001_USER_pkey PRIMARY KEY (ID_HISTORICO, ID_USER),
  CONSTRAINT CSTBH001_USER_ID_USER_USUARIO_ACAO_REGISTRO_fkey FOREIGN KEY (ID_USER_USUARIO_ACAO_REGISTRO) REFERENCES public.CSTB001_USER(ID_USER)
);
CREATE TABLE public.CSTBH002_MORADOR (
  ID_HISTORICO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_MORADOR bigint,
  ID_USER bigint,
  IC_BLOCO character varying,
  NR_APARTAMENTO integer,
  LG_ATIVO boolean,
  DH_ACAO_REGISTRO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IC_ACAO_REGISTRO character NOT NULL,
  ID_USER_AUDITOR bigint NOT NULL,
  CONSTRAINT CSTBH002_MORADOR_pkey PRIMARY KEY (ID_HISTORICO),
  CONSTRAINT CSTBH002_MORADOR_ID_USER_AUDITOR_fkey FOREIGN KEY (ID_USER_AUDITOR) REFERENCES public.CSTB001_USER(ID_USER)
);
CREATE TABLE public.CSTBH003_FUNCIONARIO (
  ID_HISTORICO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_FUNCIONARIO bigint,
  ID_USER bigint,
  ID_CATEGORIA_CARGO bigint,
  LG_ATIVO boolean,
  DH_ACAO_REGISTRO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IC_ACAO_REGISTRO character NOT NULL,
  ID_USER_AUDITOR bigint NOT NULL,
  CONSTRAINT CSTBH003_FUNCIONARIO_pkey PRIMARY KEY (ID_HISTORICO),
  CONSTRAINT CSTBH003_FUNCIONARIO_ID_USER_AUDITOR_fkey FOREIGN KEY (ID_USER_AUDITOR) REFERENCES public.CSTB001_USER(ID_USER)
);
CREATE TABLE public.CSTBH005_ENCOMENDA (
  ID_HISTORICO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_ENCOMENDA bigint,
  ID_MORADOR bigint,
  ID_FUNCIONARIO bigint,
  ID_CATEGORIA_ENCOMENDA bigint,
  DT_RETIRADO timestamp without time zone,
  LG_ATIVO boolean,
  DH_ACAO_REGISTRO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IC_ACAO_REGISTRO character NOT NULL,
  ID_USER_AUDITOR bigint NOT NULL,
  CONSTRAINT CSTBH005_ENCOMENDA_pkey PRIMARY KEY (ID_HISTORICO),
  CONSTRAINT CSTBH005_ENCOMENDA_ID_USER_AUDITOR_fkey FOREIGN KEY (ID_USER_AUDITOR) REFERENCES public.CSTB001_USER(ID_USER),
  CONSTRAINT CSTBH005_ENCOMENDA_ID_ENCOMENDA_fkey FOREIGN KEY (ID_ENCOMENDA) REFERENCES public.CSTB005_ENCOMENDA(ID_ENCOMENDA)
);
CREATE TABLE public.CSTBH009_RESERVA (
  ID_HISTORICO bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ID_RESERVA bigint,
  ID_MORADOR bigint,
  ID_LOCAL bigint,
  DT_INICIO timestamp without time zone,
  DT_FIM timestamp without time zone,
  ID_CATEGORIA_RESERVA bigint,
  LG_ATIVO boolean,
  DH_ACAO_REGISTRO timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IC_ACAO_REGISTRO character NOT NULL,
  ID_USER_AUDITOR bigint NOT NULL,
  CONSTRAINT CSTBH009_RESERVA_pkey PRIMARY KEY (ID_HISTORICO),
  CONSTRAINT CSTBH009_RESERVA_ID_USER_AUDITOR_fkey FOREIGN KEY (ID_USER_AUDITOR) REFERENCES public.CSTB001_USER(ID_USER),
  CONSTRAINT CSTBH009_RESERVA_ID_RESERVA_fkey FOREIGN KEY (ID_RESERVA) REFERENCES public.CSTB009_RESERVA(ID_RESERVA)
);
CREATE TABLE public.avisos (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  aviso character varying NOT NULL,
  data character varying NOT NULL,
  CONSTRAINT avisos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.encomendas (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  hora_entrega timestamp without time zone NOT NULL,
  remetente character varying NOT NULL,
  funcionario_id bigint NOT NULL,
  morador_id bigint NOT NULL,
  CONSTRAINT encomendas_pkey PRIMARY KEY (id),
  CONSTRAINT fk31kn3bndvuum2d07beo42q9kd FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id),
  CONSTRAINT fk6ki8pbrd66vtpt7xevq868q6g FOREIGN KEY (morador_id) REFERENCES public.moradores(id)
);
CREATE TABLE public.funcionarios (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  cargo character varying NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  nome character varying NOT NULL,
  rg character varying NOT NULL UNIQUE,
  telefone character varying NOT NULL,
  fk_user bigint UNIQUE,
  CONSTRAINT funcionarios_pkey PRIMARY KEY (id),
  CONSTRAINT fk7mf3shfr7b1j3cmxx1fh559vp FOREIGN KEY (fk_user) REFERENCES public.users(id)
);
CREATE TABLE public.locais (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  capacidade integer NOT NULL,
  nome character varying NOT NULL UNIQUE,
  CONSTRAINT locais_pkey PRIMARY KEY (id)
);
CREATE TABLE public.moradores (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  apartamento integer NOT NULL,
  bloco character NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  nome character varying NOT NULL,
  rg character varying UNIQUE,
  telefone character varying,
  fk_user bigint UNIQUE,
  CONSTRAINT moradores_pkey PRIMARY KEY (id),
  CONSTRAINT fkqr8u40httmaug4dd2knkdb697 FOREIGN KEY (fk_user) REFERENCES public.users(id)
);
CREATE TABLE public.reclamacoes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  nome character varying,
  reclamacao character varying,
  fk_morador bigint UNIQUE,
  CONSTRAINT reclamacoes_pkey PRIMARY KEY (id),
  CONSTRAINT fkb6wb7dhx4nry0qnjj87fq5bmm FOREIGN KEY (fk_morador) REFERENCES public.moradores(id)
);
CREATE TABLE public.reservas (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  data date NOT NULL,
  local_id bigint NOT NULL,
  morador_id bigint NOT NULL,
  CONSTRAINT reservas_pkey PRIMARY KEY (id),
  CONSTRAINT fkmlupau8oyqfgf4vaof15vq6l7 FOREIGN KEY (local_id) REFERENCES public.locais(id),
  CONSTRAINT fks5wsc18biv3cqiq65ae0we280 FOREIGN KEY (morador_id) REFERENCES public.moradores(id)
);
CREATE TABLE public.users (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  categoria character varying NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  senha character varying NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.visitantes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  cpf character varying UNIQUE,
  nome character varying NOT NULL,
  rg character varying NOT NULL UNIQUE,
  telefone character varying,
  funcionario_id bigint NOT NULL,
  morador_id bigint NOT NULL,
  CONSTRAINT visitantes_pkey PRIMARY KEY (id),
  CONSTRAINT fkdpuwbgbhb26ccng43u9w08a30 FOREIGN KEY (funcionario_id) REFERENCES public.funcionarios(id),
  CONSTRAINT fkl2vfmtc2icju76haimayangxc FOREIGN KEY (morador_id) REFERENCES public.moradores(id)
);