name: Release Automatica
on:
  push:
    branches:
      - main
      - NovoBackend

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Ou a versão que você usa no backend

      - name: Instalar Dependencias (Root)
        run: npm install

      - name: Validar Integridade do Pipeline
        working-directory: ./frontend/tests
        run: npm run test:pipeline

      - name: Validar Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          # Apontando para a raiz agora
          configFile: ./commitlint.config.mjs
          failOnWarnings: false

      - name: Rodar Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Roda na raiz para versionar o projeto todo
        run: npx semantic-release